### ISSUE TITLE
Validator message one at a time for selected fields when have multiple validators

### ISSUE THREAD

**Issue by danielone** [formvalidation/formvalidation#1004]
Hello, i have a case where I am validating a few fields with JS and for some of them, I want to only display 1 validator message at a time. Basically, how i can easily state and control which field shows 1 validator message and which shows more? 

in the example below, i want to only show 1 validator at a time for email and birthday but region can show both? or maybe i decide that need to show multiple validator mesages for region and email at future date. 

email: {
                validators: {
                    notEmpty: {
                        message: 'The email address is required and cannot be empty'
                    },
                    emailAddress: {
                        message: 'The email address is not a valid'
                    }
                }
            },
            password: {
                validators: {
                    notEmpty: {
                        message: 'The password is required and cannot be empty'
                    },
                    different: {
                        field: 'username',
                        message: 'The password cannot be the same as username'
                    },
                    stringLength: {
                        min: 8,
                        message: 'The password must have at least 8 characters'
                    }
                }
            },
            birthday: {
                validators: {
                    notEmpty: {
                        message: 'The date of birth is required'
                    },
                    date: {
                        format: 'YYYY/MM/DD',
                        message: 'The date of birth is not valid'
                    }
                }
            },
    region: {
                validators: {
                    notEmpty: {
                        message: 'Region is required'
                    },
                    stringLength: {
                        min: 8,
                        message: 'The password must have at least 8 characters'
                    }
                }
            },

**Comment by nghuuphuoc** [comment]
For the latest version, see the [Showing only one message each time](http://formvalidation.io/examples/showing-one-message/) example.
