### ISSUE TITLE
Run remote validation after other validations

### ISSUE THREAD

**Issue by jazzzz** [formvalidation/formvalidation#1021]
With a field of type `email` and a remote validator, the AJAX request is triggered even if the value is an invalid email. It would provide a faster feedback if the remote validator would be called only when other validations pass.

**Comment by nghuuphuoc** [comment]
@rosskevin 
Thank for the suggestion. The document is updated. 
Here are 3 ways to improve the performance when using ```remote``` validator:
http://formvalidation.io/validators/remote/#improving-the-performance
