### ISSUE TITLE
Email validation for emails with an IP address

### ISSUE THREAD

**Issue by vmuhincsod** [formvalidation/formvalidation#1075]
Hey,

Currently the email validation fails email addresses that contain an IP address in them.

So email addresses such as test@192.168.0.1 would fail.

I modified the current code slightly to allow IP addresses in the email:

From:
```
var emailRegExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
```

To:
```
var emailRegExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))|(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
```

Got the IP validation regex from here:
http://www.w3resource.com/javascript/form/ip-address-validation.php

Thought you might want to add that as a feature.

Cheers!

**Comment by nghuuphuoc** [comment]
The ```test@192.168.0.1``` email address is valid with the [latest version](http://formvalidation.io/validators/emailAddress/).
