### ISSUE TITLE
how to use BV in form wizard?

### ISSUE THREAD

**Issue by yuomtheara** [formvalidation/formvalidation#1098]
I would like to use `BV` in `form wizard`.
Please example or any plugin for form wizard.

**Comment by nghuuphuoc** [comment]
I've just added the [Playing with Fuel UX Wizard](http://formvalidation.io/examples/fuel-ux-wizard/) example.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
