### ISSUE TITLE
How to validate a Twitter Typeahead field?

### ISSUE THREAD

**Issue by duvdevan** [formvalidation/formvalidation#1109]
Is there a validator for this? I need to validate a Twitter Typeahead field, but didn't find a technique to do so by now.

Are there any custom validators for this, is there a complete bundle or can be this be done in next version of BootstrapValidator?

Thank you all.

**Comment by nghuuphuoc** [comment]
I've made a [basic example](https://rawgit.com/formvalidation/formvalidation/master/demo/typehead.html) intergrating FormValidation with Typehead 0.10.5.
The source code is located at [demo/typehead.html](https://github.com/formvalidation/formvalidation/blob/master/demo/typehead.html).
