### ISSUE TITLE
Thousand Separator

### ISSUE THREAD

**Issue by rcevs** [formvalidation/formvalidation#1112]
The 'greaterThan' attribute wasn't working with commas as thousand separator. Even in version 5.3. I had to edit line 3254:

Old: return (value + '').replace(',', '.');
New: return (value + '').replace(',', '');

Was it a bug? or did I miss something?

**Comment by nghuuphuoc** [comment]
@rcevs 
From v0.6.0, you can use the ```transfomer``` option for custom format.
See the [Modifying the value before validating](http://formvalidation.io/examples/modifying-value-before-validating/) example.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
