### ISSUE TITLE
Multiple 'Panels'

### ISSUE THREAD

**Issue by whitwa** [formvalidation/formvalidation#1117]
Hi,

I would like to use a single ASP.NET page (and therefore a single server-side form) to perform several tasks (i.e. Change Password, Change Security Questions etc.). Each task's UI would be contained within a 'panel' and each 'panel' would have it's own ASP:Button 'submit' button which would have an OnClick handler associated with it to perform the relevant task.

The issue I have is that Bootstrap Validator just sees the single form required by ASP.NET and isn't aware of the tasks/panels (i.e. groups of controls) which I have defined.

I've created an example HTML file which can be downloaded from:

https://onedrive.live.com/redir?resid=E95851224A671317!470&authkey=!AGLu_NtRRZSGcpU&ithint=file%2chtml

When you click either the Submit 1 or Submit 2 buttons, Bootstrap Validator validates the entire form (both 'panels') rather than just the fields within the same 'panel' as the 'submit' button. I would like only the fields within the same 'panel' as the 'submit' button to be validated.

Is it possible to use Bootstrap Validator in this manner?

Thanks in advance.

Regards,
Andrew

**Comment by nghuuphuoc** [comment]
v0.6.0 provides some useful method to work with wizard-like interfaces.
See some examples here http://formvalidation.io/examples/#wizard
