### ISSUE TITLE
Is there an automatic validation process?

### ISSUE THREAD

**Issue by Leobaillard** [formvalidation/formvalidation#1118]
Hi!

For starters, congrats on this amazing validator! I'm integrating it with Bootstrap and Symfony, and it's just great.

There's one thing that's been bugging my head for two days: is there a mechanism somewhere that does automatic validation when not clicking a submit button or manually submitting the form?

Let me explain: I'm trying to setup validation for a **[FuelUX Wizard](http://getfuelux.com/javascript.html#wizard)**. Thus, I have disabled live validation, hoping that I would control the form validation process completely. In addition, I've manually triggered indivudual field validation for each step (as there is no `validateContainer()` at the moment) and authorized the user to go to the next step only if `isValidContainer()` is true.

The problem is that whenever I click the "Next" button on the wizard, all the fields set up in BV are validated, even the ones in the next step, which the user is trying to access. I'm not using submit or manually validating **all** the form, so I'm wondering if this comes from BV or from FuelUX, or... somewhere else.

It's driving me crazy, I even removed all the `required` attributes from my fields, and added a `novalidate` on the form tag, but it didn't change a thing.

Any ideas?

Enclosed, my validation options:
```javascript
$('[name=site_blogbundle_post]').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		live: 'disabled',
		excluded: ':disabled',
		fields: {
			'site_blogbundle_post[title]': {
				message: 'Le titre est invalide.',
				validators: {
					notEmpty: {
						message: 'Le titre ne peut pas être vide.'
					},
					stringLength: {
						min: 6,
						max: 255,
						message: 'Le titre doit être compris entre 6 et 255 caractères.'
					},
					remote: {
						url: '{{path('site_admin_blog_ajax_checks')}}',
						message: 'Le titre est déjà utilisé.',
						type: 'POST'
					}
				}
			},
			'site_blogbundle_post[creationDate]': {
				validators: {
					date: {
						format: 'DD/MM/YYYY H:m',
						message: 'La valeur entrée n\'est pas une date valide.'
					}
				}
			},
			'site_blogbundle_post[tags][]': {
				container: '#tags-errors',
				validators: {
					notEmpty: {
						message: 'La liste de tags ne peut pas être vide.'
					},
				}
			},
			'site_blogbundle_post[headerImageName]': {
				validators: {
					file: {
						maxSize: 2097152,
						extension: 'jpg,jpeg,gif,png',
						type: 'image/jpeg,image/png,image/gif',
						message: 'Le fichier sélectionné n\'est pas valide.'
					}
				}
			},
			'site_blogbundle_post[header]': {
				validators: {
					callback: {
						message: 'L\'en-tête ne peut pas être vide.',
						callback: function(value, validator) {
							var code = $('[name="site_blogbundle_post[header]"]').code();
							alert(code);
							return (code !== '' && code !== '<p><br></p>');
						}
					}
				}
			},
		}
	})
	.on('error.field.bv', function(e, data) {
		console.log('error.field.bv -->', data);
	})
	.on('success.field.bv', function(e, data) {
		//console.log('success.field.bv -->', data);
	});
```

**Comment by tjagusz** [comment]
@nghuuphuoc any news on form wizard integration? I must do a school project and You validation plugin seems to be the best.
If You have any example showing integration with bootstrap wizard or FuelUX please share it, this would be a great start!

**Comment by nghuuphuoc** [comment]
@Leobaillard @paquitodev 
Check the new example: http://formvalidation.io/examples/fuel-ux-wizard/
