### ISSUE TITLE
Type Error in Firefox

### ISSUE THREAD

**Issue by brettjw** [formvalidation/formvalidation#1124]
I am getting an error in Firefox when I try to validate a form that is using a ckeditor - the error is "TypeError: text is undefined" on the line "return text.length >= 5;". It works fine in IE and Chrome, but Firefox is throwing an error and will not process the rest of the form. Any help would be great.

**Comment by nghuuphuoc** [comment]
@brettjw 
You can fix it as following:

```javascript
callback: {
    message: '...',
    callback: function(value, validator, $field) {
        if (value === '') {
            return false;
        }
        // Get the plain text without HTML
        var div  = $('<div/>').html(value).get(0),
            text = div.textContent || div.innerText;

        return text.length >= 5;
    }
}
```
