### ISSUE TITLE
Google recaptcha V2

### ISSUE THREAD

**Issue by Erfane** [formvalidation/formvalidation#1276]
Hello,

Thank you for your great work on bootstrapvalidator!

Would it be possible to add an example with Google Recaptcha V2?
I explicitly render the captcha -which is fine- but cannot add the validation feature.

var onloadCallback = function() {
        grecaptcha.render('html_element', {
          'sitekey' : 'your_site_key'
        });
      };

https://developers.google.com/recaptcha/docs/display#AJAX

Thanks.

**Comment by robgnyc** [comment]
Were you ever able to figure this out Erfane?

**Comment by nghuuphuoc** [comment]
@Erfane @robgnyc 
Since Google reCAPTCHA changes to new API, I have to work on upgrading the [reCAPTCHA](https://github.com/formvalidation/addon-recaptcha) add-on.
I move this issue to the add-on repos.
