### ISSUE TITLE
Invalid feedback icon shown during remote validator processing 

### ISSUE THREAD

**Issue by tmaly1980** [formvalidation/formvalidation#1279]
Instead of seeing the expected 'validating' feedback icon while a remote (ajax) validator is processing, I see an invalid icon. The icon is set to 'validating' but updateStatus() is called immediately before there is likely any response, so it's reset to 'invalid'. I've submitted a pull request (hopefully) fixing this error.

**Comment by handarueri** [comment]
i have a same problem like this, how i solve this problem ? the icon always validating not change.

**Comment by nghuuphuoc** [comment]
@handarueri 
It's fixed in the latest code. You might have to wait for v0.6.0.

**Comment by handarueri** [comment]
i have a field that use data remote validator, then i have idea for validate it using remote after success form bv. My problem is, how to create that field is false in javascript ? i mean false is that field is invalid ? how to create invalid field in javascript ?
