### ISSUE TITLE
When field is empty, submit button is disabled

### ISSUE THREAD

**Issue by jstuardo** [formvalidation/formvalidation#1283]
Hello,

I am using remote validation on a field.

When I write something in the field being remote validated it works perfectly, but when that field is empty and another required field is empty, submit is not carried out because of the required field, however, the submit button get disabled. The only way i can recover control is by writing something in the remote validated field and then remove the content in order to leave empty.

The problem is bootstrapvalidator. How can avoid the submit button being disabled?

EDIT:
Maybe bootstrapvalidator is entering in conflict with the other bootstrap validation. I was debugging disableSubmitButtons method but it is caled with disabled = true for all required fields, but when I fill the required fields, disableSubmitButtons method is never called with disabled = false

I think the solution to this is to disable validation for all fields but for remote validated field. How to achieve this?

Cheers
Jaime

**Comment by nghuuphuoc** [comment]
> How can avoid the submit button being disabled

Currently, you can archive it as following

```javascript
$(form)
    .bootstrapValidator(...)
    .on('error.field.bv', function(e, data) {
        // $(e.target)  --> The field element
        // data.bv      --> The plugin instance
        // data.field   --> The field name
        // data.element --> The field element

        data.bv.disableSubmitButtons(false);
    })
    .on('success.field.bv', function(e, data) {
        data.bv.disableSubmitButtons(false);
    });
```
