### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by rebaz88** [formvalidation/formvalidation#1284]
Hello
The invalid message of hidden fields does not disappear , after value of hidden input is set.

Thanks

**Comment by nghuuphuoc** [comment]
For hidden field, after setting value for it, you have to revalidate it manually by using [revalidateField()](http://formvalidation.io/api/#revalidate-field) method.

```javascript
// Update the hidden field value
...

// Revalidate it
$(form).bootstrapValidator('revalidateField', fieldName);
```
