### ISSUE TITLE
Add a "warning" validation state

### ISSUE THREAD

**Issue by NetbearSoftware** [formvalidation/formvalidation#1313]
Hello,

I have an input field that I would like to remote validate against the db for duplicate values. However in this instance, having a duplicate value is allowed.

I don't want to prevent the user from submitting the form, I just want to warn them.

Is it currently possible to have a "warning" validation state? ie, use the warning bootstrap classes, supply a custom message and allow the form to submit?

Tim

**Comment by nghuuphuoc** [comment]
@NetbearSoftware 
It's possible to archive it.

* First, you can use the ```remote``` validator to send the value to the back-end for checking.
If the value is already available in the database, the back-end can response an JSON encoded string of 

```
{ 
    valid: true, 
    message: 'This is a warning message'
    warning: true
}
```

The ```message``` then will be used to show in the form as usual.
The ```warning``` property is a custom one (you can change it to anything, of course) which will be used in the next section.

* Next, you can trigger events to add/remove ```has-warning``` class as following:

```javascript
$(form)
    .bootstrapValidator({
        fields: {
            userName: {
                validators: {
                    remote: {
                        url: '/path/to/back-end/'
                    }
                }
            }
        }
    })
    // This event will be triggered when the field passes given validator
    .on('success.validator.bv', function(e, data) {
        // data.field     --> the field name
        // data.element   --> the field element
        // data.result    --> the result returned by the validator
        // data.validator --> the validator name

        if (data.field === 'userName') {
            // The userName field passes the remote validator
            if (data.validator === 'remote' && data.result.warning) {
                data.element                    // Get the field element
                    .closest('.form-group')     // Get the field parent
                    .addClass('has-warning');
            }
        }
    })
    // This event will be triggered when the field doesn't pass given validator
    .on('error.validator.bv', function(e, data) {
        // We need to remove has-warning class 
        // when the field doesn't pass any validator
        if (data.field === 'userName') {
            data.element
                .closest('.form-group')
                .removeClass('has-warning');
        }
    });
```
