### ISSUE TITLE
Form's field doesn't revaildate when manually set its value to an empty string

### ISSUE THREAD

**Issue by yusiwen** [formvalidation/formvalidation#1317]
Sorry to bother, but I'm learning Bootstrap and your great work not for long, and I get a problem which I can't solve by my own:

I have a button to reset field's value to an empty string (like ''). Typing some characters into the textbox until it's value is validated, then aftering hit the reset button the value is set to empty, but the field is still validated (green OK icon on the right) and the submit button is enabled. I manually add $(#formid).bootstrapValidator('revalidateField', 'fieldname'); in the reset button click function, but it doesn't revalidate the field as well. 

I've made an example in JSFiddle: http://jsfiddle.net/xfaue10o/2/ 

Can anybody tell me how to revalidate some fields after manually set their value to an empty string?

Thanks a lot.

ps. Sorry for my poor english, if you guys get any problems reading, plz tell me.

**Comment by nghuuphuoc** [comment]
The problem is in ```$('button#reset')``` because it doesn't return the correct reset button.
I simply set ```id="resetButton"``` and change your reset code to

```javascript
$('#resetButton').click(function (e) {
    $('[name="username"]').val('');
    $('#registrationForm').bootstrapValidator('revalidateField', 'username');
});
```

and it works: http://jsfiddle.net/xfaue10o/3/

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by yusiwen** [comment]
Thank you!
