### ISSUE TITLE
Remote Option and isValid() combined do not work

### ISSUE THREAD

**Issue by donenvy** [formvalidation/formvalidation#1318]
My javascript knowledge and understanding is very basic but I have done a lot of research and got most of it working except this one bit. I am using bootstrapWizard and on clicking next button, I am using:
order.bootstrapValidator('validate');
to revalidate the field manually in case the user has refreshed the page which has retained it's form value but not validated because the user has not typed in anything. 

In my bootstrapWizard code I was expecting it would validate the field first and then run the check to see it field has been validated to get true or false.
Instead it is running the true or false code before ajax has finished loading and completed validation. 

When using this plugin http://jqueryvalidation.org remote option, .valid() it automatically checks for valid fields, re validates them including "remote" calls and if valid returns true, if not then false. I like this plugin as it fits in nicely with bootstrap but can't get it to do the same?

As result on the first button click I am getting false, and then as soon as ajax has finished loading and validation if I click the button the second time I am getting what I was expecting on the first click "true".

I have researched and believe this is due to the way ajax works in async, Whilst the other validator checks this before returning a value, I can't figure out how you make this plugin do the same

These are the two codes I am running along with what I have tried.

var orders =
$('#orders').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			stock: {
				message: 'Stock type is not valid',
				validators: {
					notEmpty: {
						message: 'Stock type is required and cannot be empty'
					},
					remote: {
						message: 'Stock is not available',
						url: 'stockavailability'
					}
				}
			} 
		}
});

$('#orders').bootstrapWizard({
	'nextSelector': '.button-next',
	'previousSelector': '.button-previous',
	onTabClick: function (tab, navigation, index, clickedIndex) {
	},
	onNext: function (tab, navigation, index) {
		order.bootstrapValidator('validate');
		if(order.data('bootstrapValidator').isValid()== false)
		{
			return false;   
		}
	},
	onPrevious: function (tab, navigation, index) {
	},
	onTabShow: function (tab, navigation, index) {
	}
});

**Comment by nghuuphuoc** [comment]
It's fixed in the [latest code](https://github.com/formvalidation/formvalidation/archive/master.zip).
The ```isValid()``` method now returns one of three values

* ```true```, if all fields are valid
* ```false```, if there is one invalid field
* ```null```, if there is at least one field which is not validated yet or being validated

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nghuuphuoc** [comment]
@donenvy 
I also added [Playing with Bootstrap Wizard](http://formvalidation.io/examples/bootstrap-wizard/) example.

**Comment by donenvy** [comment]
Thanks nghuuphuoc will check it out
