### ISSUE TITLE
Phone validator - slovak country bug

### ISSUE THREAD

**Issue by malarya** [formvalidation/formvalidation#1320]
I am reporting a bug in default Valid examples of Slovakia phone numbers:

Now Valid examples are:
00420123456789
00420 123456789
00420 123 456 789
00 420 123 456 789
+420123456789
+420 123456789
+420 123 456 789
123456789
123 456 789

Should be:
00421123456789
00421 123456789
00421 123 456 789
00 421 123 456 789
+421123456789
+421 123456789
+421 123 456 789
0123456789
012 345 67 89

Changes:
- *Country code is +421, 
- Format of "fixed-phone line": 043 586 43 21 or 0435864321

Nice day

**Comment by nghuuphuoc** [comment]
@cuchac
Can you take a look at this issue?

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nghuuphuoc** [comment]
@malarya 
> *Country code is +421

Can you give me the document/link about this change? Thank you!

**Comment by cuchac** [comment]
Apparently there was some error during merge. In https://github.com/formvalidation/formvalidation/commit/fbdf94fadd3bbebee7f864c7cb32e8e5456691b6 there is correctly 421 for SK and in final merge https://github.com/formvalidation/formvalidation/commit/e2a42b37aff56f204cfddb42721b3624aa0c9106, there is incorrectly 420 for SK.

Don't know how to simply support SK-specific "fixed-phone line" format with "0" prepended and different grouping (3 3 2 2 digits). Probably whole new regexp ORed with existing one?

**Comment by nghuuphuoc** [comment]
@cuchac 
Without making new PR, can you give me the correct regular expression for this here?

**Comment by cuchac** [comment]
For SK it should be 

`/^(((00)([- ]?)|\+)(421)([- ]?))?((\d{3})([- ]?)){2}(\d{3})$/`

It does not accept "043 586 43 21 or 0435864321" so it is not perfect. But at least it is not completely wrong :-)

**Comment by nghuuphuoc** [comment]
Thansk @malarya and @cuchac 
This issue is fixed in the latest code!
