### ISSUE TITLE
Validate text fields hidden and specific for stepwise

### ISSUE THREAD

**Issue by milindex** [formvalidation/formvalidation#1322]
As can validate text fields on a form that works in steps.

I have a form created you can see the example on this link http://jsfiddle.net/milindex/93j2bgmm/1/

Questions and doubts:

It is possible to validate text fields with BoostrapValidator but using a link or some other HTML element?
There is a link that goes to step number two, if the user does not complete the fields texts of step one, you can continue to the next step number two.

We can avoid this, is there any way to detect if the user has not completed text fields from step one, and validate by BoostrapValidator but from that link.

In step two, the user can submit the form without completing text fields step number one.
Note: Some simple manner using the tool boostrapValidator.

**Comment by nghuuphuoc** [comment]
It's not possible in v0.5.3.
From v0.6.0 (which is [renamed](http://formvalidation.io/news/v0.6.0-released/) to FormValidation), the plugin provides some useful APIs to help working with wizard-like interfaces.

See some examples at http://formvalidation.io/examples/#wizard

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
