### ISSUE TITLE
Validation triggered by Fuel UX wizard control using 'next'

### ISSUE THREAD

**Issue by fckoppenol** [formvalidation/formvalidation#1325]
It seems the form validation is automatically trigged by pressing the 'next' button using the  Fuel UX wizard control even if the control is placed outside of the control itself. 

     <!DOCTYPE html>
     <html lang="en">
     <head>
         <meta charset="utf-8">
         <title></title>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/formValidation.css" rel="stylesheet">
    <link href="css/fuelux.css" rel="stylesheet">
     </head>
     <body class="fuelux">
    <form id="productForm"  data-fv-framework="bootstrap" data-fv-icon-valid="glyphicon glyphicon-ok"  data-fv-icon-invalid="glyphicon glyphicon-remove"  data-fv-icon-validating="glyphicon glyphicon-refresh" data-fv-live="disabled">
        <div id="myWizard" class="wizard" data-initialize="wizard">
            <ul class="steps">
                <li data-step="1" class="active"><span class="badge">1</span>Campaign<span class="chevron"></span></li>
                <li data-step="2"><span class="badge">2</span>Recipients<span class="chevron"></span></li>
                <li data-step="3"><span class="badge">3</span>Template<span class="chevron"></span></li>
            </ul>
            <div class="actions">
                <button class="btn btn-default btn-prev"><span class="glyphicon glyphicon-arrow-left"></span>Prev</button>
                <button class="btn btn-default btn-next" data-last="Complete">Next<span class="glyphicon glyphicon-arrow-right"></span></button>
            </div>
            <div class="step-content">
                <div class="step-pane active sample-pane alert" data-step="1">
                    <h4>Setup Campaign</h4>
                    <p>Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion daikon amaranth tatsoi tomatillo melon azuki bean garlic. Beetroot water spinach okra water chestnut ricebean pea catsear courgette.</p>
                </div>
                <div class="step-pane sample-pane bg-info alert" data-step="2">
                    <h4>Choose Recipients</h4>
                    <p>Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard. </p>
                </div>
                <div class="step-pane sample-pane bg-danger alert" data-step="3">
                    <h4>Design Template</h4>
                    <p>Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip. Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jÃ­cama salsify. </p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>Product name</label>
            <input type="text" class="form-control" name="name"
                   data-fv-notempty="true"
                   data-fv-notempty-message="The product name is required"
                   data-fv-stringlength="true"
                   data-fv-stringlength-min="6"
                   data-fv-stringlength-max="30"
                   data-fv-stringlength-message="The product name must be more than 6 and less than 30 characters long"
                   data-fv-regexp="true"
                   data-fv-regexp-regexp="^[a-zA-Z0-9_\.]+$"
                   data-fv-regexp-message="The product name can only consist of alphabetical, number, dot and underscore" />
        </div>
        
        
    </form>

    <script src="js/jquery-1.11.2.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/formValidation.js"></script>
    <script src="js/framework/bootstrap.js"></script>
    <script src="js/fuelux.js"></script>
    <script>
        $(document).ready(function () {
            $('#productForm').formValidation({
                framework: 'bootstrap',
            });
        });
    </script>

</body>
</html>

**Comment by tjagusz** [comment]
@fckoppenol could You share a jsfiddle showing Your problem?

**Comment by nghuuphuoc** [comment]
@fckoppenol 
@tjagusz 
I've just created [Playing with Fuel UX Wizard](http://formvalidation.io/examples/fuel-ux-wizard/) example. Hope it is useful to you.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by tjagusz** [comment]
@nghuuphuoc Awesome! Exactly what we needed. Thank You.

One more question Wizard related. Can we allow Back button when there is no data on second page - validate only when clicking on "Next" "Order" buttons?

**Comment by fckoppenol** [comment]
@nghuuphuoc this works like a charm. The issue had to do with placement of the form surrounding the entire wizard control. Your demo shows the correct placement. Than you!
