### ISSUE TITLE
formValidation seems conflict with typeahead.js?

### ISSUE THREAD

**Issue by andy7ps** [formvalidation/formvalidation#1326]
As I integrate it with typeahead.js 0.10.5, if a typeahead field also set to be validate, then when I type some characters in that field, it comes an error "TypeError: $f.data(...) is undefined" in formValidation.js at line 1130, col 30. (but also typeahead not work)
Is anyway to avoid this conflict? thanks!

**Comment by pcfreak30** [comment]
I am getting this as well. It seems that even if I do it at a typeahead:closed event and force a recheck, it crashes with fv.messages data not existing. Considering I have a paid copy, I consider this pretty important.

Difference to me is typeahead works but validation crashes at it or the next field after using it.

**Comment by nghuuphuoc** [comment]
I've made a [basic example](https://rawgit.com/formvalidation/formvalidation/master/demo/typehead.html) intergrating FormValidation with Typehead 0.10.5.
The source code is located at [demo/typehead.html](https://github.com/formvalidation/formvalidation/blob/master/demo/typehead.html).

Please try it and let me know if there's something that is different with your usage.

**Comment by pcfreak30** [comment]
My issues resolved over email. Thanks @nghuuphuoc
