### ISSUE TITLE
remote validation should fail if ajax request fails

### ISSUE THREAD

**Issue by modosc** [formvalidation/formvalidation#1327]
if a remote validation hits an endpoint that returns a 4xx or 5xx the validation doesn't fail or succeed. instead the validation chain halts without any messaging. 

ideally this could be considered a failure of the validation. alternately it would be useful to be able to pass in a fail() callback for the validation to handle the situation in a custom manner.

**Comment by nghuuphuoc** [comment]
Thank for the suggestion. It's implemented in the latest code, and will be available in next v0.6.1.
