### ISSUE TITLE
Enabling submit button

### ISSUE THREAD

**Issue by bhames50** [formvalidation/formvalidation#1333]
I have a form where I disable the submit button, and only want it enabled when there is at least one valid field and no invalid fields.

I added the following code to my validator, and it works except when I tab out of an invalid field. When I do that, it enables the submit button.

            .on('err.form.fv', function(e, data) {
            	data.fv.disableSubmitButtons(true);
            })

            .on('success.form.fv', function(e, data) {
                data.fv.disableSubmitButtons(false);
            });

I also tried the following, and achieved the same results:

            .on('err.field.fv', function(e, data) {
            	data.fv.disableSubmitButtons(true);
            })

            .on('success.field.fv', function(e, data) {
            	if(data.fv.isValid()) {
                	data.fv.disableSubmitButtons(false);
            	}
            });

![invalidformsection](https://cloud.githubusercontent.com/assets/1706075/5683337/f1ea8026-97f4-11e4-889a-920735577a32.png)

As you can see in the image, the first field is invalid and I tabbed to the second field. You can also see that the submit button is enabled.

**Comment by cdomkokao** [comment]
I am having this problem as well as a problem with The submit button not working properly when fields are validated.  The submit is not working consistently.

**Comment by leonardlinde** [comment]
I am having this problem, too, with a larger, more complex form.  Smaller forms work fine.

If you want to see another example, look at your own example page. As you can see, all form fields are filled out but the submit button does not appear. This is in beta and standard Chrome on Windows, btw.

![image](https://cloud.githubusercontent.com/assets/10486857/5695616/72b21ca6-997a-11e4-89f1-5499c9da82a2.png)

**Comment by bhames50** [comment]
I'm not sure if the above example is the same problem I am having. The submit button in my case displays just fine, but is enabled while there are still fields that are invalid.

**Comment by bhames50** [comment]
@nghuuphuoc I am hoping you can give me some estimate as to when you can look into this issue. It is preventing me from releasing my application to my QA team.

**Comment by nghuuphuoc** [comment]
@bhames50 
By default, when a field is invalid, the submit button will be disabled. So, we don't need to do 

```javascript
$(yourForm)
        .formValidation(...)
        .on('err.field.fv', function(e, data) {
            data.fv.disableSubmitButtons(true);
        });
```

My approach is that trigger the ```success.field.fv``` event, which is called when the field is valid, and check if there is invalid field or not via the [getInvalidFields()](http://formvalidation.io/api/#get-invalid-fields) method:

```javascript
$(yourForm)
        .formValidation(...)
        .on('success.field.fv', function(e, data) {
            if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                data.fv.disableSubmitButtons(true);
            }
        })
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by bhames50** [comment]
I made your recommended changes, and it is working fine. Thanks again for your help!
