### ISSUE TITLE
Form is not send, validate pass with SUCCESS

### ISSUE THREAD

**Issue by paquitodev** [formvalidation/formvalidation#1341]
I have this validator config:

    $('#rpniDatosProducto')
        .find('[name="productoSolicitud[procedencia_producto]"]')
        .select2()
        .change(function (e) {
            $('#rpniDatosProducto').formValidation('revalidateField', 'productoSolicitud[procedencia_producto]');
        })
        .end()
        .find('[name="productoSolicitud[finalidad_producto]"]')
        .select2()
        .change(function (e) {
            $('#rpniDatosProducto').formValidation('revalidateField', 'productoSolicitud[finalidad_producto]');
        })
        .end()
        .find('[name="productoSolicitud[condicion_producto]"]')
        .select2()
        .change(function (e) {
            $('#rpniDatosProducto').formValidation('revalidateField', 'productoSolicitud[condicion_producto]');
        })
        .end()
        .formValidation({
            excluded: ':disabled',
            icon: {
                valid: 'fa fa-check',
                invalid: 'fa fa-times',
                validating: 'fa fa-refresh'
            },
            err: {
                container: 'popover'
            },
            fields: {
                'productoSolicitud[procedencia_producto]': {
                    validators: {
                        callback: {
                            message: "Debe seleccionar una opción.",
                            callback: function (value, validator, $field) {
                                var options = validator.getFieldElements('productoSolicitud[procedencia_producto]').val();
                                return (options != null && options.length >= 1);
                            }
                        }
                    }
                },
                'productoSolicitud[finalidad_producto]': {
                    validators: {
                        callback: {
                            message: "Debe seleccionar una opción.",
                            callback: function (value, validator, $field) {
                                var options = validator.getFieldElements('productoSolicitud[finalidad_producto]').val();
                                return (options != null && options.length >= 1);
                            }
                        }
                    }
                },
                'productoSolicitud[condicion_producto]': {
                    validators: {
                        callback: {
                            message: "Debe seleccionar una opción.",
                            callback: function (value, validator, $field) {
                                var options = validator.getFieldElements('productoSolicitud[condicion_producto]').val();
                                return (options != null && options.length >= 1);
                            }
                        }
                    }
                },
                'productoSolicitud[lote]': {
                    validators: {
                        integer: {},
                        notEmpty: {}
                    }
                }
            }
        }).on('success.form.bv', function (e) {
            e.preventDefault();
            var $form = $(e.target);
            var vf = $form.data('formValidation');
            vf.disableSubmitButtons(false);

            console.log('Something goes here');
        });

But when I hit the submit button, the `console.log()` is never executed on the Firebug console instead I get a redirection to the first page. The validation happen inside a tab in a Fuelux Wizard and I got redirected to the first tab, why? Can I get some help? I'm stucked on this point and do not know what else to go from here

**Comment by nghuuphuoc** [comment]
If you call ```. formValidation(options)```, then you have to change the event ```success.form.bv``` to ```success.form.fv```.

**Comment by paquitodev** [comment]
Right, I missed that one, thanks @nghuuphuoc
