### ISSUE TITLE
Remote validation trigger the 'err.form.fv' in version 6.0

### ISSUE THREAD

**Issue by pabluss** [formvalidation/formvalidation#1344]
If you add a remote validation anywhere, and try to submit the form always execute error.from.fv and then the form is submitted

**Comment by nghuuphuoc** [comment]
@pabluss 
Can you give me your HTML form markup and its Javascript code?

**Comment by pabluss** [comment]
<div class="container">
<div class="row">

<section>
  <div class="page-header">
  <h1>Sign up</h1>
  </div>
  <div class="col-lg-8 col-lg-offset-2">
  <form id="defaultForm" method="post" class="form-horizontal" action="target.php">
    	<div class="form-group">
	  <label class="col-lg-3 control-label">id</label>
	  <div class="col-lg-5">
	  <input type="text" class="form-control" name="id_productos" value="1" autocomplete="off" />
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-lg-3 control-label">codigo</label>
	  <div class="col-lg-5">
	  <input type="text" class="form-control" name="codigo_producto" value="BS0020" autocomplete="off" />
	  </div>
	</div>
	
	<div class="form-group">
	<div class="col-lg-9 col-lg-offset-3">
	<button type="submit" class="btn btn-primary">Submit</button>
	</div>
	</div>
  </form>
  </div>
</section>

</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
      $('#defaultForm').formValidation({
		message: 'This value is not valid',
		    // live: 'disabled',
		    icon: {
		    valid: 'glyphicon glyphicon-ok',
		    invalid: 'glyphicon glyphicon-remove',
		    validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
		    codigo_producto: {
			    message: 'The username is not valid',
			    trigger: 'blur',
			    validators: {
					notEmpty: {
					      message: 'The username is required and can\'t be empty'
					},
					remote: {
					    data: function(validator) {
                                                return { id_productos: validator.getFieldElements('id_productos').val()         };
                                            },
					    url: '../../ajax/productos_editar.php',
					}
			    }
		    }
		}
      }).on('err.form.fv', function() {
               alert('error');
      }).on('success.form.fv', function(e, data) {
	      e.preventDefault()
	      alert('send');
      });
});
</script>

------------------------------------------------------------------------
The url receive: {"valid":true}
I think the problem is that I use DB and when I load the form I have the value of inputs completed so when you submit the form, do not wait until ajax arrive and give error. Once you have the ajax received and try it again dont have the problem

**Comment by pabluss** [comment]
Any news about it? Kind regards

**Comment by nghuuphuoc** [comment]
It's fixed. You can try with the [latest code](https://github.com/formvalidation/formvalidation/archive/master.zip).

**Comment by nghuuphuoc** [comment]
__UPDATED__: 
Added [test case](https://github.com/formvalidation/formvalidation/blob/master/test/spec/submit.js#L163)
