### ISSUE TITLE
Validators order - remote should be last

### ISSUE THREAD

**Issue by Misiu** [formvalidation/formvalidation#1346]
I'm trying to implement Your awesome validation plugin inside my student project.
Right now I'm struggling with remote validation. I've added this to my fields:

            cardNumber: {
                row: '.col-lg-8',
                validators: {
                    notEmpty: {
                        message: 'Number is required!'
                    },
                    stringLength: {
                        min: 10,
                        max: 10,
                        message: 'Must have 10 digits'
                    },
                    remote: {
                        message: 'Number is invalidy',
                        delay: 1000,
                        url: '/validator',
                        type: 'POST'
                    }
                }
            }

but even if I input 2 digits I can see request done.
Can I perform remove validation only when rest of validators is valid?
I'll be very grateful for help.

**Comment by nghuuphuoc** [comment]
You can use the [verbose](http://formvalidation.io/settings/#field-verbose) option:

```javascript
cardNumber: {
    row: '.col-lg-8',
    verbose: true,
    validators: {
        ...
    }
}
```

**Comment by tjagusz** [comment]
@nghuuphuoc Thanks for fast reply. I tried that earlier, but without luck.
Maybe I'll clarify my question a bit:
I have card number field in my form, and on it 3 validators: nonEmpty, stringLength, remote.
Right now if I enter 2 digits I get error from stringLength validator, but in network tab (Chrome Development Tools - F12) I can see request done by remote validator.

I would like to to remote validation only when other validators  are valid, so in my case when I enter 10 digits and stringLenght validator will be valid I would like remote validator to check.

I ideally would like formValidation to validate field with all validator in order they are defined, in my case first would be nonEmpty, second would check length and then remote validator.

**Comment by pabluss** [comment]
same result adding:
trigger: 'blur',

**Comment by nghuuphuoc** [comment]
The document is updated. Here are 3 ways to improve the performance when using ```remote``` validator:
http://formvalidation.io/validators/remote/#improving-the-performance
