### ISSUE TITLE
Form Validator on Text stops working after i enter in text and then remove it

### ISSUE THREAD

**Issue by nirajclosedwon** [formvalidation/formvalidation#1351]
I have a form where it requires at least 3 characters be entered in for first name.  I enter in 3 characters in First Name and a checkbox icon appears validating that its ok.  When I remove a character I get an X notifying me there aren't enough characters.  But if I continue to remove all of the characters in the field, the check box comes back even though the field is blank.  The form's "Search" button is still disabled so I know the validation is still happening but the checkbox appears which can be confusing to users.  Some help on this issue would be greatly appreciated.  
![screen shot 2015-01-14 at 1 55 18 pm](https://cloud.githubusercontent.com/assets/7841858/5747416/11c07046-9bf5-11e4-9f0e-7464a5e71693.png)
![screen shot 2015-01-14 at 1 55 31 pm](https://cloud.githubusercontent.com/assets/7841858/5747421/1abf4ea6-9bf5-11e4-9376-02601e583852.png)
![screen shot 2015-01-14 at 1 55 37 pm](https://cloud.githubusercontent.com/assets/7841858/5747423/20cfb3d0-9bf5-11e4-94e9-dd5608d4b577.png)

**Comment by nghuuphuoc** [comment]
As I see, the first name is not required. What you want here is that when the field is empty, the tick icon should not be shown. Is it right?

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nirajclosedwon** [comment]
Yes, that is correct

**Comment by nghuuphuoc** [comment]
Take a look at the [Hiding success class](http://formvalidation.io/examples/hiding-success-class/) example.

**Comment by nirajclosedwon** [comment]
Thanks!  I'll take a look and post back if I have an issues.
