### ISSUE TITLE
Certain fields doesnot seems to validate

### ISSUE THREAD

**Issue by karthi89msc** [formvalidation/formvalidation#1354]
Hi , I have started used booststrap validator to validate my fields in tab. But it seems for some reason certain textbox are not being validated. I have tried for hours and could not find the reason . Would be of great help if you can take a look .Here is the fiddle http://jsfiddle.net/o2opt3cf/6/ .

You  can see that the text box "txttrial" does not validate even tough i have added it to the list .Am not sure if some class has some conflict. Thanks in advance

**Comment by nghuuphuoc** [comment]
The problem is that you set the wrong name attribute for trial field:

```html
<input type="text" placeholder="" id="txttrial" name="txtrial" class="form-control">
```

It should be ```txttrial``` (you missed a __t__):

```html
<input ... name="txttrial" ... >
```

Here is the working fiddle: http://jsfiddle.net/o2opt3cf/8/

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by karthi89msc** [comment]
Oh thanks for figuring it out. But it seems the validation symbol,error text is of different color as well as outside the text box.

**Comment by karthi89msc** [comment]
Can you please help me out on this

**Comment by nghuuphuoc** [comment]
You need to wrap the label + input inside ```.form-group```
Here is updated fiddle: http://jsfiddle.net/o2opt3cf/9/

![placing field inside form-group](https://cloud.githubusercontent.com/assets/4226036/5795855/6492986e-9fcc-11e4-8d81-d2f1c1155160.png)

**Comment by karthi89msc** [comment]
Oh :( i missed that .Thanks again .
