### ISSUE TITLE
Validation returns true and displays a tick mark but in red colour

### ISSUE THREAD

**Issue by audreyaw** [formvalidation/formvalidation#1356]
I have a group of text boxes that belongs to one field and thus validated as a group. I use callback method to validate the field and there are a few conditions that need to be checked. It also only happens if the first item in the array is empty. I am not sure whether this is a bug from the bootstrap validator or something is missing from my logic.

Below is the screenshot of the issue:
![red_tick](https://cloud.githubusercontent.com/assets/10556371/5771417/03a9a1b4-9d6f-11e4-9718-2e978d4ab5b2.png)

And the issue is not displayed when the first textbox has been filled
![green_tick](https://cloud.githubusercontent.com/assets/10556371/5771424/23feb5bc-9d6f-11e4-8101-b7a2767a0914.png)

This is the callback method that I have created:

callback : function(
		value,
		validator,
		$field) {
	var countShare = 0;
	// Get the list of fields
	$fields = validator.getFieldElements('share_percentage[]');
	for (var i = 0; i < $fields.length; i++) {
		if ($fields.eq(i).val() !== '') {
			countShare++;
		}
	}

	if (countShare < 2) {
		return {
			valid : false,
			message : [[#{error.enter.minimal}]].format(2, [[#{title.company}]])
		}
	}

	var sharePercentageList = document
			.getElementsByName("share_percentage[]");
	var totalShare = 0;
	var i = 0;
	while (sharePercentageList[i]) {
		if (isNumber(sharePercentageList[i].value)) {
			totalShare = parseFloat(totalShare)
					+ parseFloat(sharePercentageList[i].value);

			if (parseFloat(sharePercentageList[i].value) < 0
					|| parseFloat(sharePercentageList[i].value) > 100) {
				return {
					valid : false,
					message : [[#{error.between}]].format([[#{venture.sharePercentage}]], 0, 100)
				}
			}
		}
		i++;
	}

	if (totalShare != 100) {
		return {
			valid : false,
			message : [[#{error.sum}]].format([[#{venture.sharePercentage}]], '100%')
		}
	}

	
		// Update the status of callback validator for all fields
		validator
				.updateStatus(
						'share_percentage[]',
						validator.STATUS_VALID,
						'callback');
		return true;
}

I am really stuck and would really appreciate if you can help. Thanks in advance.

**Comment by nghuuphuoc** [comment]
@audreyaw 
Is this issue solved? We have just solved the similar issue #369 

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by audreyaw** [comment]
@nghuuphuoc I have already tried the method you used in #369, but unfortunately the issue can still be reproduced. I'm not sure whether this is caused by multiple validations in one callback method or not because the example you referred to only has one validation in the callback function. I have already tried removing the updateStatus function but it doesn't work.

Any other advice maybe?

**Comment by nghuuphuoc** [comment]
Based on the sample form in #369, can you give me your HTML markup form and current JS code, or a [jsfiddle](http://jsfiddle.net/) is great for me to help you!

**Comment by audreyaw** [comment]
HTML:

<form id="formAddNewVenture" class="smart-form" action="#"
								th:action="@{/venture/add}" th:object="${newVenture}"
								method="post">

								<fieldset>
									<section>
										<div class="form-group">
											<label class="label" th:text="#{table.name}">Name</label> <label
												class="input"> <input type="text" class="input-xs"
												th:field="*{name}" th:placeholder="#{table.name}"></input>
											</label>
										</div>
									</section>

									<div class="form-group">
										<table class="table table-bordered table-striped">
											<thead>
												<tr>
													
													<th th:text="#{title.company}">Company</th>
													<th th:text="#{venture.sharePercentage}">Share
														Percentage</th>
												</tr>
											</thead>
											<tbody>
												<tr th:each="company : ${listCompany}">
													
													<td th:text="${company.name}"></td>
													
													<td><input th:id="'sharePercentage' + ${company.id}"
														class="sharePercent" type="text"
														th:name="share_percentage[]"></input>%</td>
													
												</tr>
											</tbody>
										</table>
									</div>

									
								</fieldset>

								<footer>
									<button type="submit" class="btn btn-primary"
										th:text="#{global.save}">Save</button>
									<button type="button" class="btn btn-default"
										onclick="window.history.back();" th:text="#{global.back}">Back</button>
								</footer>
							</form>

JAVASCRIPT:
<script th:inline="javascript">
		//<![CDATA[
		//Select LeftMenu
		document.getElementById('menuVenture').className = 'active';
		
		$(document)
				.ready(
						function() {
							//Form Validations
							$('#formAddNewVenture')
									.bootstrapValidator(
											{
												feedbackIcons : {
													valid : 'glyphicon glyphicon-ok',
													invalid : 'glyphicon glyphicon-remove',
													validating : 'glyphicon glyphicon-refresh'
												},
												fields : {
													name : {
														validators : {
															notEmpty : {
																message : [[#{error.required}]].format([[#{table.name}]])
															}
														}
													},
													'share_percentage[]' : {
														selector : '.sharePercent',
														validators : {
															numeric : {
																message : [[#{error.number}]].format([[#{venture.sharePercentage}]])
															},
															callback : {
																callback : function(
																		value,
																		validator,
																		$field) {
																	var countShare = 0;
																	// Get the list of fields
																	$fields = validator.getFieldElements('share_percentage[]');
																	for (var i = 0; i < $fields.length; i++) {
																		if ($fields.eq(i).val() !== '') {
																			countShare++;
																		}
																	}

																	if (countShare < 2) {
																		return {
																			valid : false,
																			message : [[#{error.enter.minimal}]].format(2, [[#{title.company}]])
																		}
																	}

																	var sharePercentageList = document
																			.getElementsByName("share_percentage[]");
																	var totalShare = 0;
																	var i = 0;
																	while (sharePercentageList[i]) {
																		if (isNumber(sharePercentageList[i].value)) {
																			totalShare = parseFloat(totalShare)
																					+ parseFloat(sharePercentageList[i].value);

																			if (parseFloat(sharePercentageList[i].value) < 0
																					|| parseFloat(sharePercentageList[i].value) > 100) {
																				return {
																					valid : false,
																					message : [[#{error.between}]].format([[#{venture.sharePercentage}]], 0, 100)
																				}
																			}
																		}
																		i++;
																	}

																	if (totalShare != 100) {
																		return {
																			valid : false,
																			message : [[#{error.sum}]].format([[#{venture.sharePercentage}]], '100%')
																		}
																	}

																	
																		// Update the status of callback validator for all fields
																		if (totalShare == 100 || countShare >= 2){
																			validator
																			.updateStatus(
																					'share_percentage[]',
																					'VALID',
																					'callback');
																	return true;
																		}
																		
																		return false;
																		
																}
															}
														}
													}
												}
											});

							function isNumber(n) {
								return !isNaN(parseFloat(n)) && isFinite(n);
							}
						})
		//]]>
	</script>

**Comment by nghuuphuoc** [comment]
Please wrap the code between _```_ and _```_.
What is the version of plugin you're using?

**Comment by audreyaw** [comment]
I'm not sure how to check the version. Can you please guide me?

**Comment by nghuuphuoc** [comment]
Open the ```bootstrapValidator(.min).js``` file, and you will see the version at the top.

**Comment by audreyaw** [comment]
All I see at the top of the file is this: /*! SmartAdmin - v1.5 - 2014-09-27 */ and I'm not sure that's the version of the validator

**Comment by nghuuphuoc** [comment]
It's not the original built file.
May I look at the live site? If it's not possible to put it here, you can email me at phuoc(at)huuphuoc.me

**Comment by audreyaw** [comment]
Unfortunately we just migrated the server so currently there's no external links yet. We had one previously. The external link is still being set up. Is there any other way to figure out the version?

I can give you the link to where we got the plugin though. https://bootstraphunter.com/smartadmin-product.php

**Comment by nghuuphuoc** [comment]
Just look at the link you gave me! They don't indicate which version of plugin.
I will try to create a fiddle for it.

In our case, there are multiple fields, have the same set of validators, and:

* Require at least 2 fields
* Each of them, if defined, must be between 0 and 100 (0 <= field's value <= 100)
* Sum of them must be 100

Is there anything else?

**Comment by audreyaw** [comment]
That's about it. In the meantime, I'm gonna have a look at the code again in case I missed something. Thank you.

**Comment by audreyaw** [comment]
@nghuuphuoc Hi, is there any update on this issue?

**Comment by nghuuphuoc** [comment]
Take a look at this [jsfiddle](http://jsfiddle.net/cypvL7fv/3/) which runs with v0.5.3.

**Comment by audreyaw** [comment]
I'm going to have to ask the support for the theme that I am using whether I can update the version of the bootstrap validator. I really hope it works in my application. Thanks for your help.

**Comment by audreyaw** [comment]
Hi @nghuuphuoc, I've just found out that the theme I'm using, uses bootstrapvalidator v0.5.2. Does it mean I have to update?

**Comment by nghuuphuoc** [comment]
@audreyaw 
You don't need to update because this [fiddle](http://jsfiddle.net/cypvL7fv/4/) uses v0.5.2.
Anyway, I recommend to purchase the latest version ;), so you can use many advanced features/APIs without being worry about it.

**Comment by audreyaw** [comment]
@nghuuphuoc Hi, I think I've figured out why I can keep reproducing the bug. It has to do with the location of the form-group tag. In your sample, http://jsfiddle.net/cypvL7fv/3/, the form-group tag is placed to envelope every input box while in mine, it envelopes the table in which the input boxes are in.

Do you have any solution so that the form can still look neat the way I want without the table?

**Comment by audreyaw** [comment]
I noticed that you had closed issue #356, in which you added the validation-group tag? But somehow my bootstrapvalidator code is different? Do you mind taking a look? If you don't mind, I'll send the js file to you via email.

**Comment by nghuuphuoc** [comment]
You can use the ```group``` option.
See the updated fiddle: http://jsfiddle.net/nghuuphuoc/cypvL7fv/6/

**Comment by audreyaw** [comment]
I'd like to show the message only once. Any suggestion?

**Comment by audreyaw** [comment]
I think it has something to do with the version of bootstrap validator used in my application. I applied your code into a new page and it behaves differently with the sample you provided.

**Comment by nghuuphuoc** [comment]
> I'd like to show the message only once for the entire group of input

You can use the ```container``` option. See http://jsfiddle.net/nghuuphuoc/cypvL7fv/8/

> I think it has something to do with the version of bootstrap validator

This [fiddle](http://jsfiddle.net/nghuuphuoc/cypvL7fv/8/) uses v0.5.0.

**Comment by audreyaw** [comment]
![image](https://cloud.githubusercontent.com/assets/10556371/6035298/43a534d8-ac63-11e4-9c06-ee98db64b373.png)

Somehow in your sample, it also displays the same result with my application. The unedited input box isn't refresh and therefore displays red tick mark instead of the green one.

**Comment by audreyaw** [comment]
Hi, the issue is finally resolved. Thank you so much for your kind help. :)

**Comment by nghuuphuoc** [comment]
:+1: I'm glad that it's resolved.
