### ISSUE TITLE
How do I send hidden values to remote validation?

### ISSUE THREAD

**Issue by paquitodev** [formvalidation/formvalidation#1359]
I have a form with a hidden input as follow:

     <input type="hidden" id="productoSolicitud" name="productoSolicitud" value="7">

And I'm performing this validation:

    $('#formAddFactura').formValidation({
        icon: {
            valid: 'fa fa-check',
            invalid: 'fa fa-times',
            validating: 'fa fa-refresh'
        },
        err: {
            container: 'popover'
        },
        excluded: ':disabled',
        fields: {
            no_factura: {
                validators: {
                    notEmpty: {},
                    regexp: {
                        regexp: /^[\d]+$/,
                        message: 'El valor no es válido. Ej: 2555 ó 0001212'
                    },
                    remote: {
                        url: Routing.generate('verificarExistenciaFacturas'),
                        data: function (validator) {
                            producto_solicitud: validator.getFieldElements('productoSolicitud').val()
                        },
                        message: 'La factura ya existe para esta solicitud.',
                        delay: 1000,
                        type: 'GET'
                    }
                }
            },
            fecha_factura: {
                validators: {
                    notEmpty: {},
                    date: {
                        format: 'DD/MM/YYYY'
                    }
                }
            }
        }
    })

But I'm getting this error:

    TypeError: j is undefined
         ...function"==typeof k&&(k=k.call(this,b)),j[d.name||i]=g,d.delay?(c.data(f+".remot...

How I can send that value to the remote Ajax call?

**Comment by nghuuphuoc** [comment]
The ```data``` option of ```remote``` validator should be 

```javascript
data: function (validator) {
    return {
        producto_solicitud: validator.getFieldElements('productoSolicitud').val()
    }
}
```

**Comment by paquitodev** [comment]
Thanks, my bad
