### ISSUE TITLE
My Icon pile up each other in form-group

### ISSUE THREAD

**Issue by handarueri** [formvalidation/formvalidation#1365]
I have the problem when have two filed input group in one row, the icon for validator is pile up. This is my preview of icon that pile up
![image](https://cloud.githubusercontent.com/assets/10350870/5792051/4a4a3994-9f36-11e4-8861-3fbd89079eaf.png)

what's wrong with my code,  so that the icon is pile up. I need your help. Thank you before :)

**Comment by nghuuphuoc** [comment]
If you want to use multiple fields in the same row, use the [row](http://formvalidation.io/settings/#field-row) option.

Examples:
* http://formvalidation.io/getting-started/#complex-form
* http://formvalidation.io/examples/complex-form/

In your case, the FormValidation calling looks like

```javascript
$(form).formValidation({
    fields: {
        panjang: {
            row: '.col-sm-4',
            validators: {
                ...
            }
        },
        lebar: {
            row: '.col-sm-4',
            validators: {
                ...
            }
        }
    }
});
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by handarueri** [comment]
thank you for your reply, but when it's has no effect, my icon still pile up. 
![image](https://cloud.githubusercontent.com/assets/10350870/5797840/4030359a-9ff3-11e4-80b4-a270a15bd7e7.png)
in the javascript ,i have been added row , but does'nt have effect.

![image](https://cloud.githubusercontent.com/assets/10350870/5797853/694ada52-9ff3-11e4-8367-1bbff1f5a4df.png)


i hope you can help me, thank you :)

**Comment by nghuuphuoc** [comment]
Oh, it's my fault. Looking at the code you're using again, I realize that you're using BootstrapValidator (because of ```data-bv-xxx``` attributes).

In this case, you need to change ```row: '.col-sm-4'``` to ```group: '.col-sm-4'```.

**Comment by handarueri** [comment]
Yes you are right, its solved. Yes im still using bootstrapvalidator. Thank you so much :)) :+1:

**Comment by nghuuphuoc** [comment]
I recommend to upgrade to the FormValidation. You can close the issue now.

**Comment by handarueri** [comment]
Oke , thank you :)
