### ISSUE TITLE
Unable to load PF main page in KALI 

### ISSUE THREAD

**Issue by janspaugh** [formvalidation/formvalidation#1368]
I have installed PF on my KALI box per the installation guide listed on the PF website while also following along with the youtube video. Everything installed correctly but once I start the Apache2 website and navigate to phishingfrenzy.local all I recieve is the default Apache Webpage. 

![it works](https://cloud.githubusercontent.com/assets/10607511/5811476/c3e3c42e-a025-11e4-8af1-48a22672e872.png)

I have configured PF to run through the local loopback 127.0.0.1 and have modified the "hosts" file shown below.
![hosts](https://cloud.githubusercontent.com/assets/10607511/5811447/6125cdb4-a025-11e4-8e35-87436e485edb.png)

I have also configured the pf.conf, httpd.conf, and application.rb files to reflect this 
![pf conf](https://cloud.githubusercontent.com/assets/10607511/5811460/8af24c6c-a025-11e4-9581-3ad069b3cab7.png)

![httpd](https://cloud.githubusercontent.com/assets/10607511/5811464/934675a0-a025-11e4-89c7-a56acfe0141d.png)

![application rb](https://cloud.githubusercontent.com/assets/10607511/5811467/9a68b230-a025-11e4-84fb-8ee79fb1829e.png)

I have also included the apache2.conf file for review.

![apache2 conf](https://cloud.githubusercontent.com/assets/10607511/5811471/b74da4e6-a025-11e4-9344-f9ea438df090.png)

In addition to this I also tried disableing Apache's default webpage with no joy. Any information that you could provide would be greatly appreciated.

Thanks,
J

**Comment by nghuuphuoc** [comment]
Are you sure that you're reporting at the correct repos?
