### ISSUE TITLE
not working on Windows Phone 8.1 (Internet Explorer)

### ISSUE THREAD

**Issue by RauchenwaldC** [formvalidation/formvalidation#1370]
Why did you close issue #756 
Any feedback would be great. Are you aware of the issue? 

I'm grateful for the great work you are doing but to just close an issue without responding if you are going to look into this or are going to fix it is not the right way.

**Comment by nghuuphuoc** [comment]
@RauchenwaldC 
If I can't get enough attentions from users on the issue or don't have enough time to look at it, I will close it.
Someone found the solution but didn't get back to me. In your specific case, I will be aware of this.
