### ISSUE TITLE
Validation for hidden bootstrap fields?

### ISSUE THREAD

**Issue by anewman880** [formvalidation/formvalidation#1371]
Greetings all,

This is an amazing plugin, and I have gotten everything I need from it, except one thing. 

On my page, I have 'progressive disclosure' for some of my dropdowns in my form. In other words, certain dropdowns appear and disappear given what is selected in the dropdown above them. For example (see attached), I have a dropdown for 'State'. When the user selects a state, then the 'City' dropdown is supposed to display by removing the bootstrap css class 'hide'. The user has to select a state and a city, as they are mandatory fields. 

When I submit the form without selecting a state, I get the error for the state dropdown as expected, then when I select a state, the City dropdown appears with nothing selected, without an error message. Yes, all dropdowns have validation on them. And I cannot click submit again because the button is disabled. How am I supposed to create an error message for the user on the City dropdown when it appears? 
![error1](https://cloud.githubusercontent.com/assets/1731327/5823285/8455ebc8-a0a9-11e4-85b7-a462ea1e3d79.png)
![error2](https://cloud.githubusercontent.com/assets/1731327/5823287/87645e58-a0a9-11e4-83c6-0f8a9562ceec.png)

**Comment by anewman880** [comment]
Either that, or how would I override the plugin so that it does not disable the submit button.

**Comment by nghuuphuoc** [comment]
> how would I override the plugin so that it does not disable the submit button

Take a look at this: http://formvalidation.io/examples/enabling-submit-button/

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
