### ISSUE TITLE
.on('success.form.fv' - .on('success.form.bv'

### ISSUE THREAD

**Issue by CMedinaS7** [formvalidation/formvalidation#1372]
en  http://formvalidation.io/examples/ajax-submit/

```
$(form)
        .formValidation({
            ... options ...
        })
        .on('success.form.fv', function(e) {
            // Prevent form submission
            e.preventDefault();

            // Get the form instance
            var $form = $(e.target);

            // Get the FormValidation instance
            var bv = $form.data('formValidation');

            // Use Ajax to submit form data
            $.post($form.attr('action'), $form.serialize(), function(result) {
                // ... Process the result ...
            }, 'json');
        });
```

**Comment by nghuuphuoc** [comment]
@CMedinaS7 
Can you tell me what you want? Maybe you should update the title and description of the issue.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by CMedinaS7** [comment]
I have a method to validate a form using the example of http://formvalidation.io/examples/ajax-submit/ ..... but works did not have to change the onsucess of ".on ('success.form.fv' "a" .on ('success.form.bv' "

**Comment by nghuuphuoc** [comment]
Please give me more information, such as your HTML form markup and JS you're calling.
(Please wrap the code between _```_ and _```_)

**Comment by AndrewEastwood** [comment]
are you able to get the 'success.form.fv' event invoked on form element? I can't get it worked :disappointed:

**Comment by nghuuphuoc** [comment]
@AndrewEastwood @CMedinaS7 
Please give me more information.

**Comment by AndrewEastwood** [comment]
Just try to get the event triggered and that all. Here's what I have done:
```
    <form id="simple_form" class="form-horizontal" action="test.php" method="post">
        <div class="form-group">
            <label class="col-lg-3 control-label">Name:</label>
            <div class="col-lg-5">
                <input type="text" class="form-control" name="name"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-9 col-xs-offset-3">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    </form>

    <script>
        $(document).ready(function() {
            $('#simple_form').bootstrapValidator({
                framework: 'bootstrap',
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    name: {
                        validators: {
                            notEmpty: {
                                message: 'Name is required and cannot be empty'
                            }
                        }
                    }
                }
            }).on('success.form.fv', function(e) {
                debugger;
            });
        });
    </script>
```

And I totally can't reach debugger statement in dev-toolbar in Chrome

**Comment by CMedinaS7** [comment]
you must change the line of onsucess ".on ('success.form.fv'" a ".on ('success.form.bv' '(the' fv 'refers to formvalidation and' bv 'to bootstrapValidator)

**Comment by nghuuphuoc** [comment]
> you must change the line of onsucess ".on ('success.form.fv'" a ".on ('success.form.bv' '(the' fv 'refers to formvalidation and' bv 'to bootstrapValidator)

Exactly. See the [Upgrading guide](http://formvalidation.io/news/upgrading-to-v0.6.0/).

**Comment by nghuuphuoc** [comment]
@CMedinaS7 So, is your issue solved?

**Comment by CMedinaS7** [comment]
yes!!

the problem was the version!!!!

**Comment by nghuuphuoc** [comment]
@CMedinaS7 
So, you own me a Star for this project ;) And then, please close the issue.

**Comment by Puzik** [comment]
Thanks A LOT!!!!!
Few hours i was fighting with this forms! One letter - and so many troubles/
Thanks
