### ISSUE TITLE
Validating a non visible honeypot field is empty

### ISSUE THREAD

**Issue by robgnyc** [formvalidation/formvalidation#1374]
I'm trying to implement a honeypot field, a field that is invisible to human users but that a bot will fill in.

How do I test to see that a field which is set to display:none or visibility:hidden has nothing entered into it before submitting. Basically I want to validate the field only if it's empty. Otherwise I want the form not to submit.

**Comment by nghuuphuoc** [comment]
By default, the invisible fields will be ignored. To include this, you can set the [excluded](http://formvalidation.io/settings/#form-excluded) option.

```javascript
$(form).formValidation({
    // Only ignore disabled fields 
    excluded: [':disabled'] 
});
```

You can set ```excluded: false``` to particular field:

```javascript
$(form).formValidation({
    fields: {
        myHiddenField: {
            excluded: false, // Don't ignore me, please
            validators: { ... }
        }
    }
});
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
