### ISSUE TITLE
Destroying a validated form and re-establishing it

### ISSUE THREAD

**Issue by nsggroup** [formvalidation/formvalidation#1375]
Hi, I looked at the destroy method but I'm not achieving any results on this can any one help clarify how it is used?

My Page is AJAX driven, so depending upon how you have entered the page a different function is called upon successful validation.

I've achieved this in someway by using the code below which allows me to establish the validator but to pass a function through which is used upon success.

Problem I am having is that as the page is ajax driven you dont leave the page so once I have established the validator and something else occurs needing different validation rules I am receiving 2, 3, 4 etc submissions through validation based on the amount of times the validator is initialised.

I think this will work if I can successfully destroy the current validator before restarting it - but Im having no success with the example shown.

My code for establishing my validator sessions is as below.

```
$.fn.runValidator = function (form, action) {
        var form
        $(form)
            .bootstrapValidator({
                addOns: {
                    requiredIcon: {
                        icon: 'fa fa-asterisk'
                    }
                },
                group: '.form-group',
                feedbackIcons: {

                    valid: 'fa fa-ok',
                    invalid: 'fa fa-remove',
                    validating: 'fa fa-refresh'
                }
            })
            .on('success.form.bv', function (e) {
                // Prevent form submission
                e.preventDefault();
                if (action != null) {
                    action();
                }
            });
    };

**Comment by nghuuphuoc** [comment]
In order to destroy the validator instance, use the [destroy](http://formvalidation.io/api/#destroy) method.

```javascript
$(form).bootstrapValidator('destroy');

// Later, you can re-create it
$(form).bootstrapValidator(options);
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nsggroup** [comment]
Ah great yes thats helped - im not getting repeated submissions.

Thanks again
