### ISSUE TITLE
Validating 3 inputs as one, and comparing 2 inputs

### ISSUE THREAD

**Issue by anewman880** [formvalidation/formvalidation#1378]
Greetings all. I am trying to use this great plugin to validate a part of my form where the user enters their social security number, then re-enters their social security number (on three different text fields for each - one with three digits, two digits, then four), and validates that they match, so we're talking: 

<div class="form-group" id="ssNum">
       <label class="col-md-12 control-label" for="ssNum">Social Security Number - 3, 2, and 4</label>  
	<div class="col-md-5">
	      <input name="ssNum1" type="text" class="form-control input-md" maxlength="3">
	      <input name="ssNum2" type="text" class="form-control input-md" maxlength="2">
	      <input name="ssNum3" type="text" class="form-control input-md" maxlength="4">
	</div>
</div>

<div class="form-group" id="ressNum">
       <label class="col-md-12 control-label" for="ressNum">Re- enter Social Security Number - 3, 2, and 4</label>  
	<div class="col-md-5">
	       <input name="ressNum1" type="text" class="form-control input-md" maxlength="3">
	       <input name="ressNum2" type="text" class="form-control input-md" maxlength="2">
	       <input name="ressNum3" type="text" class="form-control input-md" maxlength="4">
	</div>
</div>

I would get an error message for each field, for a total of 3 error messages for one form group. I only want one error message for all 3 fields in each form group, no matter which of the three fields the error is in. Now, to solve that, I did try to write an if statement in my .on at the end of my fields - 

	        .on('err.validator.fv', function(e, data) {
	            if (data.field == 'ssNum1') {
	            	 data.element
		                .data('fv.messages')
		                .find('.help-block[data-fv-for="ssNum2"]').hide()
		                .find('.help-block[data-fv-for="ssNum3"]').hide();
	            }
                 });

This would hide other two error messages for each ssn form row, but then I would have to write an if statement for the other 5 input fields to hide the other two error messages. Is there a better way?? 

Oh, and how would I group the numbers on each form field together, to compare the first three ssn numbers to the second three to make sure they match? And how would I only put this error message under the re-enter social securit number group? Yikes. Thanks very much in advance. And if you're in the Atlanta area, I would definately buy you lunch one day.

![problem](https://cloud.githubusercontent.com/assets/1731327/5864773/969e8b8c-a252-11e4-9354-75820d1173f9.png)
![goal1](https://cloud.githubusercontent.com/assets/1731327/5864775/9b7794fa-a252-11e4-9647-f6c7e02c8b52.png)
![goal2](https://cloud.githubusercontent.com/assets/1731327/5864777/9ef0a5e0-a252-11e4-8522-cd63e2669c70.png)

**Comment by nghuuphuoc** [comment]
It's very good and interesting question! I will try to make an example for this, and let me know if I can get it working.

**Comment by nghuuphuoc** [comment]
@anewman880 
Take a look at this [example](https://rawgit.com/formvalidation/formvalidation/master/demo/multipleAsOne.html).
The source code is located at [demo/multipleAsOne.html](https://github.com/formvalidation/formvalidation/blob/master/demo/multipleAsOne.html).

![multiple-as-one](https://cloud.githubusercontent.com/assets/4226036/5887603/ff415398-a40c-11e4-83c6-0957cac97ccc.png)

The example shows a similar usecase, which asks to enter separated date, month and year values.
The approach is create a hidden field which its value is set from these 3 fields via ```transformer``` option.

__IMPORTANT__
This example only works with the latest code (and next v0.6.1). Although the [transformer](formvalidation.io/settings/#validator-transformer) option is available in current version (v0.6.0), but it doesn't work with notEmpty validator 
(See #1387 which is fixed in the latest code)

**Comment by nghuuphuoc** [comment]
__UPDATED__
You can make it work with current v0.6.0 by a simple trick:

```javascript
$('#profileForm')
    .formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            dob: {
                excluded: false,
                validators: {
                    notEmpty: {
                        message: 'Please fill out each field'
                    },
                    date: {
                        format: 'YYYY.MM.DD',
                        separator: '.',
                        message: 'Please enter a valid date'
                    }
                }
            }
        }
    })
    .on('keyup', 'input[name="date"], input[name="month"], input[name="year"]', function(e) {
        var y = $('#profileForm').find('[name="year"]').val(),
            m = $('#profileForm').find('[name="month"]').val(),
            d = $('#profileForm').find('[name="date"]').val();

        // Set the dob field value
        $('#profileForm').find('[name="dob"]').val(y === '' || m === '' || d === '' ? '' : [y, m, d].join('.'));

        // Revalidate it
        $('#profileForm').formValidation('revalidateField', 'dob');
    });
```

**Comment by anewman880** [comment]
Very well done, my friend.
