### ISSUE TITLE
submit button being disabled on forms without validators

### ISSUE THREAD

**Issue by alexweissman** [formvalidation/formvalidation#1379]
The 'submit' button is being disabled, despite the fact that there is only one field, and it doesn't have any validator attached to it.  See http://jsfiddle.net/h9595nm9/

**Comment by nghuuphuoc** [comment]
Thank for reporting. It's fixed.
This [fiddle](http://jsfiddle.net/h9595nm9/2/) runs with the latest code.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by alexweissman** [comment]
Awesome, thanks for the quick fix!  

By the way, I am impressed with the scope and breadth of the validation rules covered here.  Have you thought about trying to develop an official standard for form validation with W3, ANSI, etc?

**Comment by nghuuphuoc** [comment]
> Have you thought about trying to develop an official standard for form validation with W3, ANSI, etc

Not yet! It might be a good idea to think for future releases.

**Comment by alexweissman** [comment]
Well I was just thinking, it would be cool to have a common convention for specifying validation rules across different platforms, server-side as well as client-side, etc...

I'm working on a [project](https://github.com/alexweissman/bootsole/blob/master/bootsole/validation/validation.php) that will automatically generate client-side rules (in FV) and server-side rules (in Valitron) from a common set of JSON specifications.  But unfortunately there is no standard at the moment, so I'm sort of developing it based on your naming system ;-)

**Comment by nghuuphuoc** [comment]
It's in my roadmap. The [FormValidation repos](https://github.com/formvalidation/) will provide some server-side validations.
NodeJS and PHP will be supported first.

**Comment by alexweissman** [comment]
Brilliant!  Let me know if you need anyone to help out with that.
