### ISSUE TITLE
formValidation & Boostrap Wizard not working if field name is the same

### ISSUE THREAD

**Issue by cexposito** [formvalidation/formvalidation#1389]
There seems to be an issue with js, in both the isValidContainer and validateContainer method

Take a look at map[field]

            $container.find('[data-' + ns + '-field]').each(function() {
                var $field = $(this),
                    field  = $field.attr('data-' + ns + '-field');
                if (!that._isExcluded($field) && !map[field]) {
                    map[field] = $field;
                }
            });

In my boostrap wizard and can dynamically add more currency fields, i use the selector field to apply the validation. Every time i add/remove a field i destroy the formValidation plugin and reinitialize it (not sure if should be using the addField method instead)

                'good_currency[]': {
                  selector: '.good-currency',
                    validators: {
                        notEmpty: {
                            message: 'Goods currency is required.'
                        }
                    }
                },

The problem is that the map variable only records the first current input as the field value is the same for instances of this field

I updated the code as per below in both methods to use the name value, as this is unique

            $container.find('[data-' + ns + '-field]').each(function() {
                var $field = $(this),
                    field  = $field.attr('name');
                if (!that._isExcluded($field) && !map[field]) {
                    map[field] = $field;
                }
            });

This works quite well for validateContainer but not for isValidContainer as in the following line as it needs the field value, and not the name value

                                .find('.' + this.options.err.clazz.split(' ').join('.') + '[data-' + ns + '-validator][data-' + ns + '-for="' + field + '"]');

Any suggestions?

**Comment by nghuuphuoc** [comment]
Thank for reporting.
I improved both [isValidContainer()](https://github.com/formvalidation/formvalidation/blob/master/src/js/base.js#L1122) and [validateContainer()](https://github.com/formvalidation/formvalidation/blob/master/src/js/base.js#L2081) methods to support fields having the same name.

You can try to use the latest built by replacing your formValidation JS files with

```javascript
<script src="https://rawgit.com/formvalidation/formvalidation/master/dist/js/formValidation.js"></script>
<script src="https://rawgit.com/formvalidation/formvalidation/master/dist/js/framework/bootstrap.js"></script>
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by cexposito** [comment]
Your changes solved the issue of duplicate field names in the wizard

But there seems to be another issue, i see the following error:

TypeError: $field.data(...) is undefined in line 1688
	
The issue is reproducible, i add two dynamic fields, then remove them and then add another dynamic field

Every time i add or delete a dynamic field i destroy the form and then re initialize the validation plugin
    $('#form').formValidation('destroy');

**Comment by nghuuphuoc** [comment]
> The issue is reproducible, i add two dynamic fields, then remove them and then add another dynamic field

I think you should create a [jsfiddle](http://jsfiddle.net/) for it!

**Comment by nghuuphuoc** [comment]
@cexposito 
Any update on this? Help me create a jsfiddle for it, and I can reproduce the issue. It really helps me to fix the problem.

**Comment by nghuuphuoc** [comment]
I added an [example](http://rawgit.com/formvalidation/formvalidation/master/demo/tab.html) that demonstrates an usage of dynamic field and ```isValidContainer()``` method.

Adding and removing fiels are done by ```addField``` and ```removeField``` methods.
