### ISSUE TITLE
textual thing in API documentation of the 'IsValid()' method 

### ISSUE THREAD

**Issue by kikosoft** [formvalidation/formvalidation#1390]
Hi,

In the API documentation under the method 'IsValid()' it is written:

> Ensure that the validate method is already called **after** calling this one.

I think this should be:

> Ensure that the validate method is already called **before** calling this one.

It would also be nice to know what this method does when you don't comply with this rule. Is it always 'true', always 'false', or can it vary? (I found it was 'true')

**Comment by nghuuphuoc** [comment]
Thank you for reporting this. It's [fixed](http://formvalidation.io/api/#is-valid).

> It would also be nice to know what this method does when you don't comply with this rule

It returns ```true``` as you mentioned.

In next v0.6.1, the isValid() method is improved. It might returns one of three values
* ```true```, if all fields are valid
* ```false```, if there is one invalid field
* ```null```, if there is at least one field which is not validated yet or being validated
