### ISSUE TITLE
Validate on submit or click.

### ISSUE THREAD

**Issue by ctf0** [formvalidation/formvalidation#1391]
hi again ,
i have a small bug, don't know if its related to the plugin or to the code am using ,
anyway the plugin works if the event was `submit` but semi-work if it was `click`, plz take a look a the below

```js
$('a[data-target="#myModal"]').click(function(e) {
	e.preventDefault();
	var target = $(this).attr("href");

	$('.modal-content').load(target, function() {
		formvalidation();
		$("#myModal").modal('show'); // show main modal

		// submit the form ========================
		$('input[type="submit"]').submit(function(e) {
			e.preventDefault();
			$.ajax({
				type: 'POST',
				url: $(this).attr('action'),
				data: {
					id: $('input[name="id"]').val(),
					title: $('#title').val(),
					body: $('#body').val()
				},
				cache: false,
				success: function(data) {
					$("#myModal").modal('hide');  // hide main modal
					$('#msg').html('<div><strong>' + data.message + '</strong></div>');
					$("#myModal2").modal('show');  // show secondary modal
				}
			});
		});
	});
});
```

- the plugin with the above code work as expected ,but now the ajax code is being ignored.

- if we used `click` instead ,the plugin will work only if you tried to enter anything in the input fields 
but what if the input fields were empty ? 
if u clicked on the submit button the plugin wont work and now the form will be submitted via ajax.

**Comment by nghuuphuoc** [comment]
Try this [approach](http://formvalidation.io/examples/ajax-submit/):

```javascript
$('a[data-target="#myModal"]').click(function(e) {
    e.preventDefault();
    var target = $(this).attr("href");

    $('.modal-content').load(target, function() {
        $('.registerForm')
            .formValidation(options)
            .on('success.validator.fv', function(e, data) { ... })
            .on('err.validator.fv', function(e, data) { ... })
            // Here is what you need
            .on('success.form.fv', function(e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: {
                        id: $('input[name="id"]').val(),
                        title: $('#title').val(),
                        body: $('#body').val()
                    },
                    cache: false,
                    success: function(data) {
                        // bla
                    }
                });
            });

        $("#myModal").modal('show');
    });
});
```

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by ctf0** [comment]
is there a possibility to make a global option to make the plugin prevent its default submission and listen to ajax calls instead ?

the reason for that is i have a model within another so it first gets shown and on the ajax success it becomes hidden ,sorry i didn't include it in the post ,its updated now for better illustration.

**Comment by nghuuphuoc** [comment]
> is there a possibility to make a global option to make the plugin prevent its default submission and listen to ajax calls instead

It's not possible currently.

**Comment by ctf0** [comment]
i was afraid u would say that but still thanx for all ur help :) :+1: .
