### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jzaefferer** [formvalidation/formvalidation#1393]
I've looked at the LICENSE.txt in this repo and at http://formvalidation.io/license/ - based on that information, this is not free software, and running it as open source seems misleading. In addition, the repo header and the license talking about fees and buying a commercial license, but it looks like that isn't actually possible.

Afaik one of the few licenses appropriate for frontend technology like this project, in combination with commercial licenses, is [AGPL](http://www.gnu.org/licenses/agpl-3.0.html) ([details on Wikipedia](http://en.wikipedia.org/wiki/Affero_General_Public_License)). Publishing the source code as AGPL, along with a commercial license like the one you have to remove the usage restrictions, would make a lot more sense.

Anyway, it seems like right now most users have no idea about the license situation of this project, otherwise they would run away looking for something else. That isn't in anyones interest.

**Comment by nghuuphuoc** [comment]
So, if I want to keep the project as commerical as current, I should make this repos as private instead of public source?

**Comment by nghuuphuoc** [comment]
> Afaik one of the few licenses appropriate for frontend technology like this project, in combination with commercial licenses, is AGPL (details on Wikipedia). Publishing the source code as AGPL, along with a commercial license like the one you have to remove the usage restrictions, would make a lot more sense.

Ah, thank for your suggestion! I will think about this approach.
