### ISSUE TITLE
Submit incorrectly enabled even though form has errors

### ISSUE THREAD

**Issue by rosskevin** [formvalidation/formvalidation#1394]
[This jsfiddle demonstrates the problem](http://jsfiddle.net/kross/muc6y0eg/1/)

1. initial state is valid (submit enabled)
2. delete first name (submit disabled)
3. click on last name (submit disabled)
4. click on first name (submit is **enabled**) which is incorrect, the form is invalid.

[The doc](http://formvalidation.io/examples/enabling-submit-button/) states that `By default, the submit buttons will be disabled if there is at least one invalid field.`

**Comment by nghuuphuoc** [comment]
Thank for creating the jsfiddle :+1: 
Here is [working fiddle](http://jsfiddle.net/z81x9yky/1/) that runs with the latest built.
