### ISSUE TITLE
Help! Changing validator on dropdown select

### ISSUE THREAD

**Issue by mhtchong1989** [formvalidation/formvalidation#1397]
I am currently using this validator for my project. So far the validators are working flawlessly! So I have this problem: I have 4 fields in my form namely a dropdown button, a file upload field, and 2 text fields. For the sake of this post, let's disregard the 2 text fields.

I have the snippet of the bootstrapvalidator and here it is:

$('#uploadFileForm')
            .bootstrapValidator({
                live: 'enabled',
                fields: {
                    'data[Upload][uploadtype]': {
                        validators: {
                            notEmpty: {
                                message: 'Choose Upload Type'
                            }
                        }
                    },
                    'data[Upload][browsefile]': {
                        validators: {
                            notEmpty: {
                                message: 'Choose a file to upload'
                            },
                            file: {
                                extension: 'pdf',
                                type: 'application/pdf',
                                maxSize: 5120 * 5120 * 5120 * 5120 * 5120,
                                message: 'The file must be in .pdf format and must not exceed 5MB in size'
                            }
                        }
                    };

So these two validators are for the dropdown button (data[Upload][uploadtype]) and file upload field (data[Upload][browsefile]).

As you can see, my file upload field will require the user to upload a file with .pdf format and size not exceeding 5mb. This is working perfectly.

Now, what I want to do is I want to change the validator of the file upload field depending on what was chosen in the dropdown field.

For example: the user chose 'PDF' in the dropdown field and the file upload field will show the validators written above. If the user chose 'Pictures' in the dropdown field, I want the file upload field validator to change as well.

Is this possible?

**Comment by nghuuphuoc** [comment]
So, the dropdown field provides the file type (extension), and you want the ```file``` validator of ```data[Upload][browsefile]``` to change the ```extension```, ```type``` based on the selected file type?

**Comment by mhtchong1989** [comment]
Yes, exactly. I will have different kinds of file types: .jpeg, .png, .docx, .pdf, etc. So if I choose 'Pictures' in dropdown field, the file upload validator will require users to upload .jpeg or .png files. If I choose 'PDF' in dropdown field, the file upload validator will require users to upload .pdf files. And so on and so forth.

**Comment by nghuuphuoc** [comment]
You can use the [updateOption()](http://formvalidation.io/api/#update-option) method:

```javascript
$('#uploadFileForm')
    .bootstrapValidator({
        live: 'enabled',
        fields: {
            'data[Upload][uploadtype]': {
                validators: {
                    notEmpty: {
                        message: 'Choose Upload Type'
                    }
                }
            },
            'data[Upload][browsefile]': {
                validators: {
                    notEmpty: {
                        message: 'Choose a file to upload'
                    },
                    file: {
                        extension: 'pdf',
                        type: 'application/pdf',
                        maxSize: 5120 * 5120 * 5120 * 5120 * 5120,
                        message: 'The file must be in .pdf format and must not exceed 5MB in size'
                    }
                }
            }
        }
    })
    .on('change', '[name="data[Upload][uploadtype]"]', function(e) {
        // When the user change the file type
        // I assume that type can be pdf, png, jpeg, ...
        var type = $(this).val(),
            extension;

        switch (type) {
            case 'pdf':
                extension = 'application/pdf';
                break;
            case 'png':
                extension = 'image/png';
                break;
            // ...
            // Add more supported type/extension
        }

        // then set the type, extension options for data[Upload][browsefile]
        $('#uploadFileForm')
            .bootstrapValidator('updateOption', 'data[Upload][browsefile]', 'file', 'type', type)
            .bootstrapValidator('updateOption', 'data[Upload][browsefile]', 'file', 'extension', extension);
            
        // You might need to revalidate data[Upload][browsefile]
        $('#uploadFileForm').bootstrapValidator('revalidateField', 'data[Upload][browsefile]');
    });
```

**Comment by mhtchong1989** [comment]
One question. The value on the case you wrote: 'pdf' and 'png' are the value of the dropdown, right?

**Comment by nghuuphuoc** [comment]
Yes, because of using ```var type = $(this).val()```.
Anyway, you can set any value for the dropdown as long as you set the right ```type``` and ```extension``` options when using the ```updateOption``` as above.

**Comment by mhtchong1989** [comment]
Weird, it's not working. Not sure what's wrong. Let me  give you the screenshot of the view and the whole javascript of the upload form.

View:

![untitled](https://cloud.githubusercontent.com/assets/9627593/5954160/a61bbcfc-a7ce-11e4-90b6-ec8ff22c5e61.png)

So, my dropdown contains those values and I still plan on adding more if needed.

Upload Form javascript:

$('#uploadForm')
            .bootstrapValidator({
                fields: {
                    'data[Upload][type]': {
                        validators: {
                            notEmpty:{
                                message: 'Choose a Document Type'
                            }
                        }
                    },
                    'data[Upload][description]':{
                        validators: {
                            notEmpty:{
                                message: 'Description is required and must not be empty'
                            },
                            stringLength:{
                                max: 100,
                                message: 'Maximum allowable character is 100 characters only'
                            }
                        }
                    },
                    'data[Upload][file]': {
                        validators: {
                            notEmpty: {
                                message: 'You must choose a file to be uploaded'
                            }
                        }
                    }
                }
            }).on('change', '[name="data[Upload][type]"]', function(e) {
                // When the user change the file type
                // I assume that type can be pdf, png, jpeg, ...
                var selected = $(this).val(),
                    extension,
                    type,
                    message;

                switch (selected) {
                    case 'Letter of Intent':
                        extension = 'pdf';
                        type = 'application/pdf';
                        message = 'The file must be in .pdf format and must not exceed 5mb in size';
                        break;
                    case 'Photographs of Facilities':
                        extension = 'png';
                        type = 'image/png';
                        message = 'The file must be in .png format and must not exceed 5mb in size';
                        break;
                    // ...
                    // Add more supported type/extension
                }

                // then set the type, extension options for data[Upload][browsefile]
                $('#uploadForm')
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'type', type)
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'extension', extension)
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'message', message);

                // You might need to revalidate data[Upload][browsefile]
                $('#uploadForm').bootstrapValidator('revalidateField', 'data[Upload][file]');
            });

**Comment by nghuuphuoc** [comment]
Maybe you need to ```console.log(selected)``` to see its value.
Here is working [fiddle](http://jsfiddle.net/8y3cfpr3/2/).

**Comment by mhtchong1989** [comment]
Ok, I think it is kinda working. But the 'message' won't show. It's giving me the default error 'Please choose a valid file'. The others are working though. 

I choose 'Letter of Intent' which must be in .pdf format. I upload a file in .pdf format and no error. Choose a file with any format: .exe, .doc, .png and error appears.

I choose 'Photographs of Facilities' which must be in .png format. I upload a file in .png format and no error. Choose a file with any format: .exe, .pdf, .txt and the error appears.

I don't know why the it's giving me the default error.

**Comment by mhtchong1989** [comment]
Still not working. I tried comparing the one on JSFiddle and mine. It's basically the same but with different naming.

Here's the updated JSfiddle: http://jsfiddle.net/8y3cfpr3/6/

I also put null on the file and it is still working. 

$('#uploadForm')
            .bootstrapValidator({
                fields: {
                    'data[Upload][type]': {
                        validators: {
                            notEmpty:{
                                message: 'Choose a Document Type'
                            }
                        }
                    },
                    'data[Upload][description]':{
                        validators: {
                            notEmpty:{
                                message: 'Description is required and must not be empty'
                            },
                            stringLength:{
                                max: 100,
                                message: 'Maximum allowable character is 100 characters only'
                            }
                        }
                    },
                    'data[Upload][file]': {
                        validators: {
                            notEmpty: {
                                message: 'You must choose a file to be uploaded'
                            },
                            file: {
                                extension: null,
                                type: null,
                                maxSize: null,
                                message: null

                            }
                        }
                    }
                }
            }).on('change', '[name="data[Upload][type]"]', function(e) {
                // When the user change the file type
                // I assume that type can be pdf, png, jpeg, ...
                var selected = $(this).val(),
                    extension,
                    type,
                    max_size,
                    message;

                switch (selected) {
                    case 'Letter of Intent':
                        extension = 'pdf';
                        type = 'application/pdf';
                        max_size = 5120 * 5120 * 5120 * 5120 * 5120;
                        message = 'The file must be in .pdf format and must not exceed 5mb in size';
                        break;
                    case 'Photographs of Facilities':
                        extension = 'png';
                        type = 'image/png';
                        max_size = 5120 * 5120 * 5120 * 5120 * 5120;
                        message = 'The file must be in .png format and must not exceed 5mb in size';
                        break;
                    // ...
                    // Add more supported type/extension
                }

                // then set the type, extension options for data[Upload][browsefile]
                $('#uploadForm')
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'extension', extension)
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'type', type)
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', 'maxSize', max_size)
                    .bootstrapValidator('updateOption', 'data[Upload][file]', 'file', message);

                // You might need to revalidate data[Upload][browsefile]
                $('#uploadForm').bootstrapValidator('revalidateField', 'data[Upload][file]');
            });

**Comment by mhtchong1989** [comment]
It's finally working! I just missed something. Instead of 'updateMessage' I put 'updateOption'.

Thank you for the help! Really Appreciate it!

**Comment by nghuuphuoc** [comment]
:+1: I forgot to mention it. Although the fiddle uses it :)

**Comment by nghuuphuoc** [comment]
Thank for your question.
I added [Updating validator options](http://formvalidation.io/examples/updating-validator-options/) example and hopefully, it can help other users.
