### ISSUE TITLE
feedback glyphicon at a wrong position with form-group-sm 

### ISSUE THREAD

**Issue by AnnoyingTechnology** [formvalidation/formvalidation#1398]
```html
<div class="form-group form-group-sm">
	<label class="control-label col-md-4">
		Ville
	</label>
	<div class="col-md-8">
		<input type="text" name="city" value="whatever " class="form-control" required />
	</div>
</div>
```
![screen shot 2015-01-29 at 13 51 24](https://cloud.githubusercontent.com/assets/5336824/5957868/b777dacc-a7be-11e4-81b4-949b49690dc6.png)

It works fine with the default input size, but as soon as you switch to -sm it doesn't follow
I have seen this possible solution : https://github.com/formvalidation/formvalidation/issues/1377

But maybe there is an option to detect if the group is -sm -xs, -lg without having to adjust the feedback offset manually ? thanks

**Comment by nghuuphuoc** [comment]
I'm afraid that we must do it manually. For 2 reasons:
* To make the plugin thin
* Bootstrap doesn't support it.
Below is how the icons look (taken from http://getbootstrap.com/css/#forms-control-validation) when I add ```form-group-xx``` to the ```form-group``` div:

![feedback-icon](https://cloud.githubusercontent.com/assets/4226036/5958086/aa1f305c-a7f3-11e4-8fd0-470ccfafe14d.png)

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by AnnoyingTechnology** [comment]
Ok, thanks for answering !
