### ISSUE TITLE
using Bootstrap-select v1.6.3

### ISSUE THREAD

**Issue by haldiggs** [formvalidation/formvalidation#1401]
I'm not sure if something has changed between the examples using 1.3.2 and 1.6.3 now. As long as all I render is the normal 

			<select name="language" id="language" class="form-control">
				<option value=""></option>
				<option value="arabic">Arabic</option>
				<option value="english">English</option>
				<option value="french">French</option>
				<option value="german">German</option>
				<option value="other">Other</option>
			</select>
The validation works as expected. However as soon as I run/add the selectpicker()

			<select name="language" id="language" class="form-control selectpicker ">
				<option value=""></option>
				<option value="arabic">Arabic</option>
				<option value="english">English</option>
				<option value="french">French</option>
				<option value="german">German</option>
				<option value="other">Other</option>
			</select>

`$('.selectpicker').selectpicker();`

Then the validations fail to work. I still see the helper span is created. I think it has something to do with the selector. It doesn't seem to matter whether the controls is in a complex for or not. Or if I use the `row:` selector or not.

Has anyone else encountered this issue?

**Comment by nghuuphuoc** [comment]
When integrating FormValidation with other plugin, you should follow these [principles](http://formvalidation.io/examples#compatibility).
Here is an example showing how to integrate with Bootstrap Select:
http://formvalidation.io/examples/bootstrap-select/

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by haldiggs** [comment]
yes I was looking at that. I have set that up. When you exec  `$('.selectpicker').selectpicker();` the html in the page changes. You then end up with the traditional bootstrap dropdown consisting of the `<a>` link above a `<ul>` and then the validation fails to work. Maybe this was different in your experience.

	<div class="container" style="max-width:500px;">
		<div class="row">
			<form id="movieForm" method="get" action="test.htm">
				<div class="form-group">
					<div class="row">
						<div class="col-xs-8">
							<label class="control-label">Movie title</label>
							<input type="text" class="form-control" name="title" />
						</div>

						<div class="col-xs-4 selectContainer">
							<label class="control-label">Language</label>
							<select name="language" id="language" class="form-control">
								<option value=""></option>
								<option value="arabic">Arabic</option>
								<option value="english">English</option>
								<option value="french">French</option>
								<option value="german">German</option>
								<option value="other">Other</option>
							</select>
						</div>
					</div>
				</div>

				<button type="submit" class="btn btn-default">Validate</button>
			</form>
		</div>
	</div>
validation works on this as it sits... but then try running
`    $('#language').selectpicker();`
which creates the bootstrap html. then validation stops working. As far as I know this is how to setup and run Bootstrap Select. I will do anything to make this work.

**Comment by haldiggs** [comment]
thanks for any help though, I forgot to say that.

**Comment by nghuuphuoc** [comment]
I'm sorry for responding late.
Since the field is placed inside ```<div class="col-xs-4">```, you need to use the [row](http://formvalidation.io/settings/#field-row) option.

Here is working [fiddle](http://jsfiddle.net/nghuuphuoc/4unyeLd8/5/).

![bootstrap select](https://cloud.githubusercontent.com/assets/4226036/6119764/dfb67166-b0ff-11e4-9471-59b6ca5abbab.png)
