### ISSUE TITLE
Problem with reading default messages from correct localization file

### ISSUE THREAD

**Issue by budik21** [formvalidation/formvalidation#1404]
After implementing 0.6.1 I have problem with reading default messages

Base on preferred language I set correct localization file on application start

    <?php    	
    	switch (strtolower($_SESSION['LANG'])) {
     		case 'cs':
     			echo "<script type='text/javascript' src='js/language/cs_CZ.js'></script>";
     	   		break;
     		case 'sk':
     			echo "<script type='text/javascript' src='js/language/sk_SK.js'></script>";
                        break;
    	}
    ?>

The result is, that in case of Czech language I have in rendered HTML page this line:

    <script type='text/javascript' src='js/language/cs_CZ.js'>

...and the link is correct and leads to formvalidation localization resource.

Next I  have following piece of code

    <input type="text"
          class="form-control"
          name="polluxusername"
          id="polluxUsername"
          placeholder="<?php echo $localization->getLocalizationByCode('20'); ?>"
                                 
          data-fv-notempty="true"
          data-fv-notempty-message="<?php echo $localization->getLocalizationByCode('11');?>"
                                 
          data-fv-stringlength="true"
 	  data-fv-stringlength-min="6"
	  data-fv-stringlength-max="20"
					 			 
  	  data-fv-regexp="true"
	  data-fv-regexp-regexp="^[a-zA-Z0-9_-]*$"
	  data-fv-regexp-message="<?php echo $localization->getLocalizationByCode('161');?>"
    >

So, it means, that in two cases I  set message programaticalyy, but in case of wrong string length I would like to use default formvaliatin message. **But the message is displayed in English, not in Czech language, although I have set correct localization package.**

What I am doing wrong?

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#9
