### ISSUE TITLE
Server-side validation after form submit

### ISSUE THREAD

**Issue by BenGiroux** [formvalidation/formvalidation#1409]
First of all, thank you for creating a fantastic plugin that makes validation with HTML5 so easy!

Quick question: Is there an easy way to do form validation after the form is submitted via AJAX? While the validation on-the-fly is a nice feature, I’d hoped that there was a fallback validation on the server end that would pass back a JSON string indicating which fields failed and update them accordingly. 

I’m currently doing it manually and copying the CSS styles for the errors…

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#13
