### ISSUE TITLE
Using Ajax-Bootstrap-Select

### ISSUE THREAD

**Issue by nevits8as** [formvalidation/formvalidation#1411]
I cant validate the select field whit Ajax-Bootstrap-Select. In the same form i can validate others field but its just this one what i cant

(((STRUCTURE)))
<div class='col-xs-12'>
                    <div class='form-group' style='display:block' id='seek'>
                    <label>Seek</label>
<select id='co_seek' name='co_seek' class='selectpicker with-ajax' data-live-search='true' data-width='100%'></select>
</div>

(((SCRIPT)))
$(document).ready(function() {
    $('#frm_antecedep')
		.find('[name="co_seek"]')
			  .selectpicker()
			  .change(function(e) {
				  $('#frm_antecedep').formValidation('revalidateField', 'co_seek');
			  })
			.end()
        .formValidation({
			framework: 'bootstrap',
			excluded: [':disabled', ':hidden', ':not(:visible)'],
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
               	co_seek: {
                    validators: {
                        notEmpty: {
                            message: 'Please select your native language.'
                        }
                    }
                },
            }
        });
});

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#16
