### ISSUE TITLE
How can I validate two array inputs with identical or different validator.

### ISSUE THREAD

**Issue by berwite** [formvalidation/formvalidation#1412]
I have a dynamic fields name victim and respondent .How can I validate the fields whether
the array inputs victim has the same value in the array inputs respondent. 

![image](https://cloud.githubusercontent.com/assets/8809661/6053407/df5fb8c4-ad19-11e4-8e60-fdabbe082288.png)

this should validate that the input userteacher should be different in respondent userteacher

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#17
