### ISSUE TITLE
Allow multiple phone country types

### ISSUE THREAD

**Issue by JoeAlamo** [formvalidation/formvalidation#1413]
Hi.
Is there any way at all to allow more than one country type for phone validation? So that if it matches any of the countries listed it is counted as valid?

For example,
validators: {
    phone: {
        country: 'GB|US|ES'
    }
}

or an option to allow ANY?

Kindest regards,
Joe

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#18
