### ISSUE TITLE
Question: How to dynamically make div tag visible on dropdown select?

### ISSUE THREAD

**Issue by mhtchong1989** [formvalidation/formvalidation#1414]
I have this form with a lot of input fields. One of the input fields is a dropdown menu wherein once the user selects one, I want 2 additional input fields to appear below it.

Here is the screenshot of the form:

![untitled](https://cloud.githubusercontent.com/assets/9627593/6091310/2ced77fc-aee1-11e4-9c03-1f0ff421aff3.png)

As you can see in the screenshot, I have already put the two input fields: Government Permit and Government Recognition Number. By default, I want both of them to be hidden (without taking the space while hidden). They will only appear once the 'Existing' option is selected. If 'New' is selected, nothing happens.

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#22
