### ISSUE TITLE
Custom Container / Adding up values

### ISSUE THREAD

**Issue by jacobkossman** [formvalidation/formvalidation#1416]
Hey. Thanks for this plugin. I have a situation where I want to validate a set of sliders which represent a percentage and I want to validate them to add up to 100 in total. I currently am populating a hidden field with javascript to get the value of all the slider and using the identical validator to compare it with another hidden field with a static value of 100. Is there a better way to do this? Include them all as the same field value and do it that way?

Also if I'm doing it correctly then I'd need a custom error container and I can only figure out how to get ALL messages to show up in a specific container not on a field by field basis. 

Thanks.

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#20
