### ISSUE TITLE
Display feedback for user during a remote validation

### ISSUE THREAD

**Issue by chetzof** [formvalidation/formvalidation#1419]
Some validation might take pretty long time, and currently there is not way to let the user know that the validation is still in process.  What about something like this?

```
remote: {
  url: 'url'
  delay: 1,
  callback: function(promise){
   $('.progress').text('Please wait, we are checking....');
    promise.always(function(){
       $('.progress').text('Ready');
    });
  }
}
```

**Comment by nghuuphuoc** [comment]
Thank for the suggestion. Actually, it's a bug which the validating icon isn't shown when the remote validator is doing its job. See #1107, #1280
This bug is fixed in the latest code, and will come with next v0.6.1.

**Comment by chetzof** [comment]
thanks!
