### ISSUE TITLE
Email Address Validation error

### ISSUE THREAD

**Issue by biapar** [formvalidation/formvalidation#1421]
Hi,
I tried to validate  an email field, but there is an error when validate the input. The plugin validate an email value like this "pippo@pippo" without a correct domain.
Maybe is there a regex rule error?

![schermata 2015-02-12 alle 18 46 04](https://cloud.githubusercontent.com/assets/661517/6173345/78c13b46-b2e7-11e4-8b4e-eabf7bf0270a.png)

**Comment by nghuuphuoc** [comment]
Actually, it's valid email address.
The [Is a@b valid email address](http://formvalidation.io/validators/emailAddress/#is-ab-valid-email-address) section will help you.

![email address](https://cloud.githubusercontent.com/assets/4226036/6180276/11ef7e5a-b355-11e4-8d44-c0acf4c54436.png)


---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_

**Comment by nghuuphuoc** [comment]
In next v0.6.1, you can use external service such as Mailgun to validate the email address.
See https://github.com/formvalidation/formvalidation/issues/1315#issuecomment-71214822
Live example is also [available](https://rawgit.com/formvalidation/formvalidation/master/demo/mailgun.html)
