### ISSUE TITLE
Font Awesome icon classes for UiKit

### ISSUE THREAD

**Issue by neriv** [formvalidation/formvalidation#1423]
Hi, thought it should be noted that if the icons do not appear for UiKit it's because, Uikit uses the a custom class of uk-icon-* for the font awesome icons not fa.

so <pre>
framework: 'uikit',
        icon: {
             required: 'fa fa-asterisk',
            valid: 'fa fa-check',
            invalid: 'fa fa-times',
            validating: 'fa fa-refresh'
        },
</pre>

should be...
<pre>framework: 'uikit',
icon:{    
           required: 'uk-icon-asterisk',
            valid:'uk-icon-check',
            invalid: 'uk-icon-times',
            validating: 'uk-icon-refresh'
    },</pre>

**Comment by nghuuphuoc** [comment]
@neriv 
Thank a lot for your suggestion. I've updated the UIKit icon usage in both the [icon](http://formvalidation.io/settings/#form-icon) settings and all examples of the [Writing form](http://formvalidation.io/getting-started/#writing-form) section.

---
_If FormValidation is useful to you, please Star this project, and [Buy it](http://formvalidation.io/download/) :heart:_
