### ISSUE TITLE
Validate From only Some Buttons

### ISSUE THREAD

**Issue by cdomkokao** [formvalidation/formvalidation#1428]
I have a form with multiple buttons.  One is an input type submit and another is a button.  Both of these buttons are invoking the validations and I only want the submit buttons to do it.  Is there a way to exclude buttons from the running of form validations?  I am having trouble using the button syntax that is in the guide.  Any help would be greatly appreciated.

**Comment by cdomkokao** [comment]
To add to this, I was trying to do this but it didn't work.

	$('#createAccountBack').on('click', function() {
		var validator = $('.mainForm').data('bootstrapValidator');
	    validator.enableFieldValidators(false);
	});

I get the following error.

Uncaught TypeError: Cannot read property 'validators' of undefined.

**Comment by nghuuphuoc** [comment]
> One is an input type submit and another is a button. Both of these buttons are invoking the validations and I only want the submit buttons to do it

By default, only ```type="submit"``` buttons do the validation tasks. ```type="button"``` won't.
If you use BootstrapValidator, it is set by ```submitButtons``` setting.
In FormValidation, it's [button](http://formvalidation.io/settings/#form-button) setting.

I think there's trouble with your usage somewhere. Can you please create a [jsfiddle](http://jsfiddle.net/) for me?

**Comment by cdomkokao** [comment]
The way these are being called is pretty complicated.  It might be hard for me to fiddle it.  I can paste the code here.  Maybe that would help?  I have a JS file called validations.js that looks through the form and finds fields that are marked with certain CSS classes.  When it finds them, it puts the HTML5 version of the validation logic on the fields.  In this way, I can define validations for any field in the app if the appropriate CSS class or classes are applied.

    $(document).ready(function() {
	// Required Validation
	$('.vRequired').attr( {
	    "data-bv-notempty":true,
	    "data-bv-notempty-message":"This field is required.",
	});

	// Email Validation
	$('.vEmail').attr( {
	    "data-bv-emailaddress":true,
	    "data-bv-emailaddress-message":"The email address is not valid."
	});

    // SSN Validation
    $('.vSSN').attr( {
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^(?!(000|666|9))\\d{3}-(?!00)\\d{2}-(?!0000)\\d{4}$",
        "data-bv-regexp-message":"The format of your SSN is invalid. It should be XXX-XX-XXXX."
    });

    // License Validation
    $('.vDlNumber').attr( {
        "data-bv-stringlength":true,
        "data-bv-stringlength-min":9,
        "data-bv-stringlength-max":15,
        "data-bv-stringlength-message":"Driver's license must be at least %s and %s characters.",
    });

    // Alpha Validation
    $('.vAlpha').attr( {
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^\\s*([a-zA-Z]*)\\s*$",
        "data-bv-regexp-message":"Please enter only alphabet characters in this field."
    });

    // Numeric Validation
    $('.vNumeric').attr( {
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^\\s*([0-9]*)\\s*$",
        "data-bv-regexp-message":"Please enter only number characters in this field."
    });

    // Alpha-Numeric Validation
    $('.vAlphaNumeric').attr( {
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^\\s*([0-9a-zA-Z]*)\\s*$",
        "data-bv-regexp-message":"Please enter only alphabet or numbers in this field."
    });

    // Zip Code Validation
    $('.vZip').attr( {
        "data-bv-zipcode":true,
        "data-bv-zipcode-country":"US",
        "data-bv-zipcode-message":"Please enter a valid zip code."
    });

    // Phone Validation
    $('.vPhone').attr( {
        "data-bv-phone":true,
        "data-bv-phone-country":"US",
        "data-bv-phone-message":"Please enter a valid phone number."
    });

    // VIN Validation
    $('.vVIN').attr( {
        "data-bv-vin":true,
        "data-bv-vin-message":"Please enter a valid VIN number."
    });

    // Credit Card Validation
    $('.vCreditCard').attr( {
        "data-bv-creditcard":true,
        "data-bv-creditcard-message":"Please enter a valid credit card number."
    });

    // Date Validation
    $('.vDate').attr( {
        "data-bv-date":true,
        "data-bv-date-message":"Please enter a valid date."
    });

	// URL Validation
	$('.vURL').attr( {
        "data-bv-uri":true,
        "data-bv-uri-message":"Please enter a valid URL."
	});

    // Case Number Validation
    $('.vCaseNumber').attr( {
        "data-bv-stringlength":true,
        "data-bv-stringlength-min":9,
        "data-bv-stringlength-max":9,
        "data-bv-stringlength-message":"Case number must be 9 characters.",
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^\\s*([0-9]*)\\s*$",
        "data-bv-regexp-message":"Please enter only number characters in this field."
    });

    // Password Validation
    $('.vPassword').attr( {
        "data-bv-stringlength":true,
        "data-bv-stringlength-min":8,
        "data-bv-stringlength-message":"Your password must be at least 8 characters.",
    });

    // Username Validation
    $('.vUsername').attr( {
        "data-bv-identical":true,
        "data-bv-identical-field":"txtEmailAddress",
        "data-bv-identical-message":"Your confirmation email doesn\'t match your email address."
    });

    // Must have at least one lower case alpha.
    $('.vLowerCaseAlpha').attr( {
        "data-bv-regexp":true,
        "data-bv-regexp-regexp":"^(?=.*[a-z].*)([a-zA-Z0-9]+)$",
        "data-bv-regexp-message":"Please enter at least one lowercase alpha character."
    });

    $('.mainForm')
    .bootstrapValidator({
        feedbackIcons: {
            valid: 'false',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'false'
        },
        fields: {
            // Validator that ensures that the confirmation email matches the original email.
            txtConfirmEmail: {
                validators: {
                    identical: {
                        field: 'txtEmailAddress',
                        message: 'Your confirmation email doesn\'t match your email address.'
                    }
                }
            },
            // Validator that ensures that the confirmation password matches the original password.
            txtPasswordConfirm: {
                validators: {
                    identical: {
                        field: 'txtPassword',
                        message: 'Your confirmation password doesn\'t match your password.'
                    }
                }
            },
            // Validator that ensures that the password field has the correct values based on the password policy.
            txtPassword: {
                validators: {
                    callback: {
                        callback: function(value, validator, $field) {
                            if (value === value.toLowerCase()) {
                                return {
                                    valid: false,
                                    message: 'Your password must contain at least one uppercase character.'
                                }
                            }
                            if (value === value.toUpperCase()) {
                                return {
                                    valid: false,
                                    message: 'Your password must contain at least one lowercase character.'
                                }
                            }
                            if (value.search(/[0-9]/) < 0) {
                                return {
                                    valid: false,
                                    message: 'The password must contain at least one digit'
                                }
                            }
                            if (value.search(/[\~\!\@\#\$\%\^\&\*\_\-\+\=\`\|\\\(\)\{\}\[\]\:\;\"\'\<\>\,\.\?\/]/) < 0) {
                                return {
                                    valid: false,
                                    message: 'The password must contain at least one of the following symbols ~ ! @ # $ % ^ & * _ - + = ` | \ ( ) { } [ ] : ; \" \' < > , . ? /'
                                }
                            }
                            if (value.length < 8) {
                                return {
                                    valid: false,
                                    message: 'Your password must be more than 8 characters long.'
                                };
                            }

                            return true;
                        }
                    }
                }
            }
        }
    });
    });

My HTML page has 2 buttons, one that has input type = submit and one that has just a button tag.  The button doesn't even post the form, but the validations are still being fired off.

**Comment by cdomkokao** [comment]
On a separate question, since I pasted the code in here, I would like to have the callback options in my IF statement above return all conditions at once... that is to say, when a user starts putting in the password field, I want all of the messages to display and go away as they are satisfied rather than the way it is now where it only shows one message at a time.  Is that possible with the callback function?

Thank you so much for your help.

**Comment by nghuuphuoc** [comment]
> My HTML page has 2 buttons, one that has input type = submit and one that has just a button tag. The button doesn't even post the form, but the validations are still being fired off

It's quite strange. What's the version of plugin you're using? Can you give me your form HTML?

**Comment by cdomkokao** [comment]
I am currently using v0.5.0.  I will copy the code in tomorrow when I get back into work.  Unfortunately, I cannot upgrade to the new FV version because that would require too many changes right now and I couldn't get the approvals by the client.

**Comment by nghuuphuoc** [comment]
> that is to say, when a user starts putting in the password field, I want all of the messages to display and go away as they are satisfied

I moved to formvalidation/support#37

**Comment by nghuuphuoc** [comment]
> I am currently using v0.5.0. I will copy the code in tomorrow when I get back into work

Do you have this for me?

**Comment by cdomkokao** [comment]
It is tricky to get the HTML from the page.  We are using Spring framework with some framework pieces...  I think this is working again somehow.  I will let you know if I can't get it to work in the future.  Thank you for the help.  I will close this for now.
