### ISSUE TITLE
Date Validator - support for '.' as seperator

### ISSUE THREAD

**Issue by marvkis** [formvalidation/formvalidation#1444]
Hi,

in Europe we have many countries that have a '.' as Date-Seperator like DD.MM.YYYY.

In the src/js/validator/date.js the validator tries to automatically detect the seperator in line 83, but it only tests for '-' and '/' as candidate. Can you add support to also test for an '.' as seperator, like
separator = (date.indexOf('/') !== -1) ? '/' : ((date.indexOf('-') !== -1) ? '-' : ((date.indexOf('.') !== -1) ? '.' : null));

Thanks & Bye,
     marvkis

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#44
