### ISSUE TITLE
onSuccess called mulitple times on remote validation

### ISSUE THREAD

**Issue by andyhbg** [formvalidation/formvalidation#1447]
When using remote validation combined with onSuccess callback the function is called every time the submit button is pressed. The remote url is not fetched again but onSuccess is called. Is this the expected behavior?

```javascript
$('#frm-register').formValidation({				
      live:'enabled',
      fields: {		    	
          'card-nr': {
              verbose: false,
              validators: {
                  notEmpty: {
                        message: 'Error'
                  },
                  numeric: {
                       message: 'Error'
                  },
                  stringLength: {
                       min: 8,
                       max: 8,
                       message: 'Error'
                  }, 
                  remote: {
                      url: '',
                      type: 'GET',                															
                      onSuccess: function(e, data) {
                          // Called every time submit button is pressed
                          console.log('onSuccess', data);
                      },
                      onError: function(e, data) {
                          console.log('onError');
                      }
                  }
              }
          }
      }
})
.on('success.form.fv', function(e) {
})
```

**Comment by cigzigwon** [comment]
where is the url params defined? you have nothing in it so how can it call anything?

**Comment by andyhbg** [comment]
Sorry, I removed it before I posted. That´s not the problem, the validation works and the server call is made when the card number field changes. My problem is that the onSuccess function is called every time i submit the form. There is no extra call to the server but the function is called.

**Comment by cigzigwon** [comment]
Did you try messing with the delay option for that validator?

**Comment by cigzigwon** [comment]
Are you passing the valid key back?

**Comment by andyhbg** [comment]
No I haven't but the Ajax request is fine. Everything works fine with the validation every time the field is updated. The problem is that the onSuccess function is called on form submission. There is no Ajax request, but onSuccess is called regardless

**Comment by cigzigwon** [comment]
so make like a dev and set the delay to 0, try somethign man, include more info too you sound like a bot

**Comment by andyhbg** [comment]
I have tried several things multiple times. Now I really just want to know if it's the expected behavior.

From what I can understand from the manual the default value of delay is 0. 
*By default, the plugin will send an Ajax request to your back-end whenever you enter a character in field*

Regardless, I have now tried to set delay to 0 and the same problem still exist. For now, I think I simply must deal with the event firing on form submission.

**Comment by cigzigwon** [comment]
I cannot find the default for delay or where it is set.... prolly zero which disables it. the internal method will not call if it is zero... because it checks if (options.delay) did you try a one perhaps?? like I suggested doing and you still didn't report what you did throughly, I don't support this lib but if I did I'd find ur comment as a nuisance

**Comment by andyhbg** [comment]
I'm sorry if I have offended you or anyone else! My initial question was whether this was a expected behavior. Surely someone could answer it without debugging my code. But here is my cleaned code so that the error hopefully can be reproduced. I use jQuery 2.1.3, Bootstrap 3.3.2 and FormValidation 0.6.1

If I enter a (any) number in the card number the field is validated exactly as intended. onSuccess is called for each change. For test the server returns json {"valid": true} When I press the "Register" button the onSuccess function executes one last time. There is no Ajax request made, only execution of onSuccess. Then success.form.fv executes

```
<form role="form" name="frm-visits" id="frm-visits">
  <div class="form-group">
    <label class="control-label">Card number</label>
    <input type="text" class="form-control" name="card-nr" data-user-id="" />					
  </div>												
  <div class="control-group clearfix">
    <label class="control-label"></label>
    <div class="controls">
      <button type="submit" class="btn btn-success pull-right">
        Register
      </button>
    </div>
  </div>								
</form>

<script>

$(function () {

  $('#frm-visits').formValidation({				
    framework: 'bootstrap',
    icon: {
      valid: 'glyphicon glyphicon-ok',
      invalid: 'glyphicon glyphicon-remove',
      validating: 'glyphicon glyphicon-refresh'
    },
    fields: {
      'card-nr': {
        verbose: false,
        validators: {
          remote: {
            url: '/admin-gc/_server/cards-validate.php',
            delay: 0,								
            type: 'GET',                
            onSuccess: function(e, data) {
              console.log('onSuccess');                  
            }
          }
        }
      }
    }	    	
  })
  .on('success.form.fv', function(e) {
    e.preventDefault();
    console.log('success');                  
  });												        			
});

</script>

```

**Comment by cigzigwon** [comment]
it's not offensive it just wastes time if you don't share more code or concise thoughts, if you don'rt speak English I apologize... did you try a delay of 1 like I said?

**Comment by andyhbg** [comment]
Yes, I have tried to set delay to 1, 2, 5, 10 but with the same result! I have no other solution than to leave it as is for the moment. If it´s a bug it will hopefully be solved eventually. At the moment I resolve it through a bit of extra code in. Not as beautiful as it could have been but it works

Thanks for your help!

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#70
