### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by san360** [formvalidation/formvalidation#1449]
Hello,

I am getting this error " Uncaught TypeError: Cannot read property 'find' of undefined"

I have a multiple forms in a web page and i am using twitter typeahed for auto complete. The validation fails for the auto complete controls.

Please advice.

![image](https://cloud.githubusercontent.com/assets/6613457/6509302/c26c4506-c35e-11e4-931e-98ca98a27153.png)

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#51
