### ISSUE TITLE
Enable validation on hidden field value?

### ISSUE THREAD

**Issue by toolsmith** [formvalidation/formvalidation#1451]
Thanks for a great plugin! I have one question before I purchase.  I'm using typeahead with some geocode values and want to validate the parent field "location" based on a hidden value that gets updated when a user selects a location from the drop down list.  Is this possible?

My hidden two fields look like this:

    <form name="form" id="geoInfoForm">
        <fieldset id="geo-data">
            <input type="hidden" id="lat" name="lat" value="">	
	    <input type="hidden" id="lng" name="lng" value="">
	</fieldset>
    </form>

The location field that should display the field looks like this:

    <div class="form-group">
         <input type="text" class="form-control" name="location" id="location">
    </div>

It gets updated via:

    $("#location").geocomplete({
        details: "#geo-data",
       	types: ["geocode", "establishment"],
    });

Can I validate the location field based on valid values from the hidden lat and lng fields?

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#54
