### ISSUE TITLE
Excluded option on a field should support filters

### ISSUE THREAD

**Issue by phlegx** [formvalidation/formvalidation#1453]
The ```excluded``` option on a field can only be of type boolean (v0.6.1). It can be very useful if the option can also be of type filter like in the ```excluded``` option of a form. Here an example:

```javascript
    ...
      fields: {
        'field_one': {
          excluded: false
        },
        'field_two': {
          excluded: function(field, validator) {
            return !field.closest('fieldset').is(':visible');
          }
        }
     }
```

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#62
