### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by roryprimrose** [formvalidation/formvalidation#1458]
Any chance of removing the jQuery dependency? jQuery is very heavy to pull in when the site only requires it for this library. Alternatively, would this library still work if jQuery was swapped out with the cash jQuery replacement?

**Comment by cigzigwon** [comment]
Hey man... satrt looking in the code.

v0.6.2-dev
if (typeof jQuery === 'undefined') {
    throw new Error('FormValidation requires jQuery');
}

so I guess that means he already did bronad.

**Comment by cigzigwon** [comment]
I don't see it in there correct me if I'm wrong.

**Comment by cigzigwon** [comment]
maybe it's diffrent if you purchased the download package lib? I used bower.

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#69
