### ISSUE TITLE
Skip validation on specific submit button (multiple submit buttons on form)

### ISSUE THREAD

**Issue by metaxos** [formvalidation/formvalidation#1461]
Hi.

First things first... Thank you for your work, this is a superbe tool.

We have a form with 3 submit buttons (back, next and overview). Clicking back and next should trigger the validation. If the user clicks the overview button, the form should be submitted but the validation should be skipped.

How would be the best approach to resolve this issue?

Regards
metaxos

**Comment by cigzigwon** [comment]
go to the documentation and follow the wizard examples.... if you have trouble with .validate() then use .validateContainer(container*) #1460 shows custom button example and that is used with multiple buttons

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#71
