### ISSUE TITLE
How to skip a validation of empty field?

### ISSUE THREAD

**Issue by budik21** [formvalidation/formvalidation#1462]
I would like to ask you for an advice for following case

1. I have a field, which is optional (DOESN'T contain data-fv-notempty="true" option)
2. On this field is for instance regexp validator, which is triggered in case, that some char is typed into a filed or in case that submit button is pressed, like this:

        <input type="text"
         class="form-control"
         name="someName
         id="someId"
	       
         data-fv-regexp="true"
         data-fv-regexp-regexp="some regexp"
         data-fv-regexp-message="some message">

In this case, after submit button press, this field is validated and mark as "success".

My wish is skip validation of this type of fields in case, that there is empty value?

I have read many advices, but it seems to be complicated for such a easy thing.

Thanks for advice and regards
Radek Budar

**Comment by nghuuphuoc** [comment]
This issue was moved to formvalidation/support#68
