### ISSUE TITLE
Submitting form is not POSTing, only validating.

### ISSUE THREAD

**Issue by jamesallison** [formvalidation/formvalidation#1463]
When I click my Save Changes button, the form gets validated, but most of the time does not POST. Why is this? It does sometimes post if I change the dropdown value, however whenever I change just the text field values it validates, ticks the field, disables the submit button but does not POST.

    <?php
	session_start();
	// must be logged in
	if(!isset($_SESSION['loggedin'])) {
		header('location: /login.php?from=/editserver.php');
		exit();
	}
	// check server actually exists
	require('includes/mysql.php');
	$id = intval(strip_tags(mysql_real_escape_string($_GET['id'])));
	$query = mysql_query("SELECT * FROM servers WHERE id='$id'");
	if(mysql_num_rows($query)!=1) {
		header('location: /myservers.php');
		exit('Could not edit server, server not found!');
	}
	$server = mysql_fetch_assoc($query);
    ?>
    <!DOCTYPE html>
    <html lang="en">
	<head>
		<?php include_once('includes/head.php');?>
		<title>FMS</title>
		<link rel="stylesheet" href="/assets/css/formValidation.min.css"/>
	</head>
	<body>
		<div class="container" style="max-width:1200px;">
			<?php
				include_once('includes/navbar.php');
			?>
			<div class="row">
				
				<div class="col-md-2">
					<ul class="nav nav-pills nav-stacked" id="editTabs">
						<li class="active"><a href="#details"><i class="fa fa-list-ul"></i> Details</a></li>
						<li><a href="#address"><i class="fa fa-server"></i> Address</a></li>
						<li><a href="#description"><i class="fa fa-pencil"></i> Description</a></li>
						<li><a href="#banner"><i class="fa fa-picture-o"></i> Banner</a></li>
						<li><a href="#votifier"><i class="fa fa-thumbs-up"></i> Votifier</a></li>
					</ul>
					<hr>
					<a href="/server/<?php echo $id;?>" class="btn btn-default col-lg-12 col-md-12 col-sm-12 col-xs-12"><i class="fa fa-eye"></i> View Server</a><br /><br />
					<a href="/addserver.php" class="btn btn-default col-lg-12 col-md-12 col-sm-12 col-xs-12"><i class="fa fa-plus"></i> Add Server</a><br /><br />
					<a href="/myservers.php" class="btn btn-default col-lg-12 col-md-12 col-sm-12 col-xs-12"><i class="fa fa-server"></i> My Servers</a>
				</div>
				
				
				<div class="col-md-10">
					<div class="tab-content">
						<div class="tab-pane fade in active" id="details">
							<h1>Details</h1>
							<?php
								if(!empty($_SESSION['edit_details_errors'])) {
									echo '<div class="alert alert-danger"><ul>';
									foreach ($_SESSION['edit_details_errors'] as &$value) {
										echo "<li>$value</li>";
									}
									echo '</ul></div>';
									unset($_SESSION['edit_details_errors']);
								}
							?>
							<form id="details" action="/scripts/edit_details.php" method="post">
								<div class="form-group">
									<label class="control-label" for="name">Name (required, 5-30 characters)</label>
									<input type="text" class="form-control" id="name" name="name" placeholder="Server Name" value="<?php echo $server['name'];?>">
								</div>
								<div class="form-group">
									<label class="control-label" for="url">Website URL</label>
									<input type="text" class="form-control" id="website" name="website" placeholder="Website URL" value="<?php echo $server['website'];?>">
								</div>
								<div class="form-group">
									<label class="control-label" for="country">Country</label>
									<select class="form-control" name="country">
										<option value="selectone" disabled="" selected="">--Select a Country--</option>
										<?php
											// loop thru countries
											require('includes/mysql.php');
											mysql_set_charset("utf8");
											$query = mysql_query("SELECT * FROM countries ORDER BY countryName ASC");
											while($country = mysql_fetch_assoc($query)) {
										?>
										<option value="<?php echo $country['countryCode'];?>"<?php if($server['country']==$country['countryCode']) {echo ' selected';}?>><?php echo $country['countryName'];?></option>
										<?php
											}
										?>
									</select>
								</div>
								<input type="hidden" name="serverid" value="<?php echo $server['id'];?>">
								<button type="submit" class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">Save Changes</button>
							</form>
						</div>
						<div class="tab-pane fade" id="address">
							<h1>Address</h1>
							<form id="address" action="/scripts/edit_address.php" method="post">
								<div class="form-group">
									<label class="control-label" for="ip">Server IP (required)</label>
									<input type="text" class="form-control" id="ip" name="ip" placeholder="Server IP (without port)" value="<?php echo $server['ip'];?>" required>
								</div>
								<div class="form-group">
									<label class="control-label" for="port">Server Port (required)</label>
									<input type="text" class="form-control" id="port" name="port" placeholder="Server Port (default 25565)" value="<?php echo $server['port'];?>" required>
								</div>
								<input type="hidden" name="serverid" value="<?php echo $server['id'];?>">
								<button type="submit" class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">Save Changes</button>
							</form>
						</div>
						<div class="tab-pane fade" id="description">
							<h1>Description</h1>
							<form id="description" action="/scripts/edit_description.php" method="post">
								<div class="form-group">
									<label class="control-label" for="description">Description (max 2000 characters)</label>
									<textarea class="form-control" rows="3" id="description" name="description" style="height:350px;" placeholder="A brief or detailed description of your server (Max 2000 characters)"><?php echo $server['description'];?></textarea>
								</div>
								<input type="hidden" name="serverid" value="<?php echo $server['id'];?>">
								<button type="submit" class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">Save Changes</button>
							</form>
						</div>
						<div class="tab-pane fade" id="banner">
							<h1>Banner</h1>
							<?php if($server['bannerext']!=NULL) {?>
							<img src="/assets/img/serverbanners/<?php echo md5($server['time_created'].$id).'.'.$server['bannerext'];?>" alt="<?php echo $server['name'];?>" style="max-width:468px;width:100%;height:60px;"><br />
							<?php }?>
							<form id="banner" action="/scripts/edit_banner.php" method="post">
								<div class="form-group">
									<label for="banner">Server banner (468x60)</label>
									<input type="file" id="banner" name="banner">
								</div>
								<input type="hidden" name="serverid" value="<?php echo $server['id'];?>">
								<button type="submit" class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">Save Changes</button>
							</form>
						</div>
						<div class="tab-pane fade" id="votifier">
							<h1>Votifier</h1>
							hi
						</div>
					</div>
				</div>
			</div>
			
			<footer class="footer">
				<?php include_once('includes/footer.php');?>
				<script href="/assets/js/bootstrap-formhelpers-countries.js"></script>
				<script href="/assets/js/bootstrap-formhelpers-selectbox.js"></script>
			</footer>
		</div> 
		<?php include_once('includes/foot.php');?>
		<script type="text/javascript" src="/assets/js/formValidation.js"></script>
		<script type="text/javascript" src="/assets/js/formValidationBootstrap.js"></script>
		<script>
			$('#editTabs a').click(function (e) {
				e.preventDefault()
				$(this).tab('show')
			});
			
			$(document).ready(function() {
				$('#details').formValidation({
					framework: 'bootstrap',
					icon: {
						valid: 'fa fa-check',
						invalid: 'fa fa-times',
						validating: 'fa fa-spinner fa-pulse'
					},
					trigger: 'change',
					fields: {
						name: {
							validators: {
								stringLength: {
									min: 5,
									max: 30,
									trim: true,
									message: 'Server name must be 5-30 characters long'
								},
								notEmpty: {
									message: 'This is a required field'
								}
							}
						},
						website: {
							validators: {
								uri: {
									allowEmptyProtocol: true,
									protocol: 'http, https',
									message: 'Must be a valid website address',
									delay: 2000
								}
							}
						},
						country: {
							validators: {
								notEmpty: {
									message: 'Please select a country'
								},
							}
						}
					}
				});
				
			});
		</script>
	</body>
    </html>

**Comment by nghuuphuoc** [comment]
Answered on formvalidation/support#67
