### ISSUE TITLE
Selector by Class not working for me.

### ISSUE THREAD

**Issue by DarkAllMan** [formvalidation/formvalidation#369]
I can't seem to get this to work using a selector by class........
Somehow no error message is shown but validation is false ( red fields and red tabhead ), even when it should be ok... its just always red.....
All other validation in the form work great.... just not this part.

			<div class="form-group">
			  <label for="a_qtysep" class="col-lg-2 control-label">Qty September</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=100 type="text" class="form-control input-small text-right input-integer percent" name="a_qtysep" id="a_qtysep" value="<?php echo escape($headerData->a_qtysep); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtymar" class="col-lg-2 control-label">Qty March</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=106 type="text" class="form-control input-small text-right input-integer percent" name="a_qtymar" id="a_qtymar" value="<?php echo escape($headerData->a_qtymar); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="a_qtyoct" class="col-lg-2 control-label">Qty October</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=101 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyoct" id="a_qtyoct" value="<?php echo escape($headerData->a_qtyoct); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtyapr" class="col-lg-2 control-label">Qty April</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=107 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyapr" id="a_qtyapr" value="<?php echo escape($headerData->a_qtyapr); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="a_qtynov" class="col-lg-2 control-label">Qty November</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=102 type="text" class="form-control input-small text-right input-integer percent" name="a_qtynov" id="a_qtynov" value="<?php echo escape($headerData->a_qtynov); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtymay" class="col-lg-2 control-label">Qty May</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=108 type="text" class="form-control input-small text-right input-integer percent" name="a_qtymay" id="a_qtymay" value="<?php echo escape($headerData->a_qtymay); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="a_qtydec" class="col-lg-2 control-label">Qty December</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=103 type="text" class="form-control input-small text-right input-integer percent" name="a_qtydec" id="a_qtyjun" value="<?php echo escape($headerData->a_qtyjun); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtyjun" class="col-lg-2 control-label">Qty June</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=109 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyjun" id="a_qtyjun" value="<?php echo escape($headerData->a_qtyjun); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="a_qtyjan" class="col-lg-2 control-label">Qty January</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=104 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyjan" id="a_qtyjan" value="<?php echo escape($headerData->a_qtyjan); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtyjul" class="col-lg-2 control-label">Qty July</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=110 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyjul" id="a_qtyjul" value="<?php echo escape($headerData->a_qtyjul); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="a_qtyfeb" class="col-lg-2 control-label">Qty February</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=105 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyfeb" id="a_qtyfeb" value="<?php echo escape($headerData->a_qtyfeb); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			  <label for="a_qtyaug" class="col-lg-2 control-label">Qty August</label>
			  <div class="col-lg-2">
				<div class="input-group">
					<input tabindex=111 type="text" class="form-control input-small text-right input-integer percent" name="a_qtyaug" id="a_qtyaug" value="<?php echo escape($headerData->a_qtyaug); ?>" autocomplete="off" maxlength="3">
					<span class="input-group-addon">&#37;</span>
				</div>
			  </div>
			</div>

And the validation part is:

										percentage: {
											selector: '.percent',
											validators: {
												notEmpty: {
													message: 'Phasing percentage cannot be empty!'
												},
												callback: function(value, validator) {
													var percentage = validator.getFieldElements('percentage'),
														length = percentage.length,
														sum = 0;

													for (var i = 0; i < length; i++) {
														sum += parseFloat($(percentage[i]).val());
													}
													if (sum == 100) {
														validator.updateStatus('percentage', 'VALID', 'callback');
														return true;
													}
													
													return false;
												}
											}
										}

**Comment by DarkAllMan** [comment]
After being pulled away from this project for some time, I'm back. Purchased 0.6.0 and trying to implement the 12 fields sum = 100% with live validation again. Can you help me get this working?

**Comment by nghuuphuoc** [comment]
@DarkAllMan
The [demo/selector2.html](https://rawgit.com/formvalidation/formvalidation/master/demo/selector2.html) example works with v0.6.0.
Is this what you need?

**Comment by DarkAllMan** [comment]
Thx, with your example I found out what the difference was between mine and your solution.
It stopped working as soon as I used the following property: maxlength="3"

**Comment by nghuuphuoc** [comment]
@DarkAllMan 
By default, when using ```maxlength``` attribute, the plugin will [enable](http://formvalidation.io/examples/html5/) the stringLength validator on it automatically.
In this case, you can remove the ```maxlength``` attribute or set ```data-fv-stringlength="false"``` to disable the validator.

**Comment by DarkAllMan** [comment]
so how can I limit the max input then?

**Comment by nghuuphuoc** [comment]
> It stopped working as soon as I used the following property: maxlength="3"

I need to reproduce this on my example first. At the moment, I have no idea why your app doesn't work since we don't update the status of ```stringLength``` validator.

**Comment by DarkAllMan** [comment]
Im live and waiting anxious ;)

**Comment by nghuuphuoc** [comment]
I updated the [demo/selector2.html](https://rawgit.com/formvalidation/formvalidation/master/demo/selector2.html) example. Now each percent field requires at least 2 characters by using the ```stringLength``` validator.

Please take a look at it.

**Comment by DarkAllMan** [comment]
That's not what I meant....
We are talking about percentages... which means none of the fields can hold more than 3 characters....
So I want to limit the input to max 3 characters.... 
You are talking about a minimum :)

**Comment by nghuuphuoc** [comment]
I'm sorry, it's my fault. I updated the [demo/selector2.html](https://rawgit.com/formvalidation/formvalidation/master/demo/selector2.html) example.

Thank for your feedback, I need to improve a little bit the latest code (which don't set the icon for the field having not yet validated validator).

**Comment by DarkAllMan** [comment]
My question is more basic actually..... I just want to use the normal HTML Tag:
http://www.w3schools.com/tags/att_input_maxlength.asp

**Comment by DarkAllMan** [comment]
so you cannot even type 4 characters ;)

**Comment by nghuuphuoc** [comment]
Yes, I know how ```maxlength``` attribute works. 
I know the reason causing our problem when using both selector and HTML 5 attributes.

Behind the scene, when calling ```.formValidation()``` on form, the plugin will loop though the field having ```name``` attribute, and check if the field have HTML 5 attributes. If yes, it will use the ```name``` attribute, and set ```data-fv-field="name of field, not the selector"``` attribute which uses the name attribute, not the selector.

Therefore, some checking will not working.

So, at the moment, we must remove the ```maxlength``` attribute, and apply ```stringLength``` validator as in the latest code of example.

**Comment by DarkAllMan** [comment]
ok, thx for your answer!
