### ISSUE TITLE
how to validate fields with <input type="button"

### ISSUE THREAD

**Issue by abuzer-firdousi-confiz** [formvalidation/formvalidation#590]
I have a signup widget, a large form divided into 3 steps, i need to validate the first part when user clicks on 'Next' button, i do not want to validate complete the form.
any hint?

**Comment by nghuuphuoc** [comment]
@abuzer-firdousi-confiz 
v0.6.0 comes with some methods supporting wizard-like components
http://formvalidation.io/examples/#wizard
