### ISSUE TITLE
Validator level settings

### ISSUE THREAD

**Issue by zoner14** [formvalidation/formvalidation#973]
Right now settings only exist at the form and field levels. I am running into a scenario where validator level settings makes a lot of sense. I have an email address field that has two validators: one checks that the input is a properly formed email address, and the second queries the server using a remote call to ensure that the email address has not been used.

Right now, I have live validating enabled. Obviously I cannot query the server before the entire email address is entered. This is where a trigger kicked off by the blur event comes into play. But the moment I start using a trigger is moment my first validator stops working until the user loses focus on the form. This is not what I'm looking for. Is there a standard workaround for this issue? 

Here is my thought. Keep both validators around, but the remote call validator starts disabled. Then attach an event to the email input field that is fired when focus is lost. The callback to this event would enable the remote call validator and then call the revalidateField function from the API.  Any thoughts on the feasibility of this plan? Are there easier alternatives?

**Comment by nghuuphuoc** [comment]
@zoner14 
See http://formvalidation.io/validators/remote/#improving-the-performance
